### ISSUE TITLE
Handshake failure when using TLS

### ISSUE THREAD

**Issue by ArmandGrillet** [docker/swarm#1023]
I'm trying to make a simple configuration (one master, one node) using Docker Swarm over TLS.
Master's IP address: `192.168.42.21` and node's IP address: `192.168.42.22`, both virtual machines are on Debian with Docker 1.7. 

Running Swarm without TLS is working on the virtual machines. My method to create a Swarm is to change `/lib/systemd/system/docker.service` in `node` to listen on `tcp://0.0.0.0:2375` and then run Swarm in `master`. I'm trying to do the same with TLS enabled but its not working, here is my procedure: 

I created the certificates on my main machine using an auto-signed certificate, here is the full procedure:

On my machine:
```zsh
openssl genrsa -aes256 -out ca.key 2048
openssl req -new -x509 -days 365 -key ca.key -sha256 -out ca.crt
echo subjectAltName = IP:192.168.42.21,IP:192.168.42.22 > extfile.cnf
```

On `master`:
```zsh
openssl genrsa -out master.key 2048
openssl req -subj "/CN=192.168.42.21" -new -key master.key -out master.csr
openssl x509 -req -days 365 -in master.csr -CA /vagrant/ca.crt -CAkey /vagrant/ca.key -CAcreateserial -out master.crt -extfile /vagrant/extfile.cnf
```

Same procedure for `node` to have `node.key` and `node.crt`.

Now I'm changing `/lib/systemd/system/docker.service` in  `node` to have the line:
```zsh
ExecStart=/usr/bin/docker -d --tlsverify --tlscacert=/vagrant/ca.crt --tlscert=/home/vagrant/node.crt --tlskey=/home/vagrant/node.key -H fd:// -H tcp://0.0.0.0:2375
```

I'm reloading `docker` in `node`:
```zsh
sudo systemctl daemon-reload
sudo /etc/init.d/docker restart
```

`docker ps` is working on the node.

I'm starting Swarm in the `master` after checking that the old `swarm` container is not running anymore:
```zsh
docker run -v /vagrant:/vagrant -v ~:/etc/cert/ -d -p 2375:2375 swarm manage --tlsverify --tlscacert=/vagrant/ca.crt --tlscert=/etc/cert/master.crt --tlskey=/etc/cert/master.key 192.168.42.22:2375
```

The container is running but here are the logs:
```zsh
vagrant@master:~$ docker logs focused_lovelace 
time="2015-07-03T15:15:16Z" level=info msg="Listening for HTTP" addr=":2375" proto=tcp 
time="2015-07-03T15:15:16Z" level=error msg="Get https://192.168.42.22:2375/v1.15/info: remote error: handshake failure"
```

My auto-signed certificate seems correct as I've followed the [documentation](https://docs.docker.com/articles/https) so it could be a bug in Docker Swarm.

**Comment by jsipprell** [comment]
You're free to do things exactly as your prefer, of course, but if I might suggest something that could _potentially_ make your life much easier:

*Containerize certificate creation and deployment* (and, in the process, possible switch away from using openssl for certificate or CSR generation)

A good place to start is w/ the `ehazlett/cert-tool` container. Here's how I did it (from scratch):

* `mkdir -p ~/docker/bootstrap; cd ~/docker/bootstrap`
* `docker run --name cert-tool -t -v $(pwd):/tmp ehazlett/cert-tool -d /tmp --tls-ca-org 'My Docker/Swarm CA'`
* `docker cp cert-tool:/bin/cert-tool bin`

At this point you will have new ca.pem, client-key.pem and client.pem files that you can use as you see fit in your ~/.docker for client purposes. Leave the ca.pem and ca-key.pem files in the directory, but do whatever you want with the client cert/keys. `/bin/cert-tool` will end up in your final image but we can't base the image directly off of `ehazlett/cert-tool` because there is no shell in that image.

* Create a new `Dockerfile` in the current directory with the following contents:

    ```Dockerfile
    FROM busybox
    VOLUME [".tls"]
    ADD . /
    WORKDIR /etc/docker
    CMD cert-tool -d /.tls --tls-ca-org 'My Docker/Swarm CA' \
                       --tls-ca-cert /ca.pem --tls-ca-key /ca-key.pem \
                       --server $IPADDRESS --server $HOSTNAME && \
                       cp -f /.tls/ca.pem . && cp -f /.tls/server.pem cert.pem && \
                       cp -f /.tls/server-key.pem key.pem
    ```

* [_OPTIONAL_] Create another container to manage swarm certs, the key is that they must be both web client *and* web server certs (unless you are not using --tlsverify at various places). Example `Dockerfile`, assuming you build the above image and named it `bootstrap`

    ```Dockerfile
    FROM bootstrap
    CMD cert-tool -d /.tls --tls-ca-org 'My Docker/Swarm CA' \
                        --tls-ca-cert /ca.pem --tls-ca-key /ca-key.pem \
                        --server $IPADDRESS --server $HOSTNAME \
                        --server swarm-leader.service.consul && \
                        cp -f /.tls/server.pem swarm.pem && \
                        cp -f /.tls/server-key.pem swarm-key.pem
    ```

> > *NB*: The `swarm-leader.service.consul` is only there because I'm using consul for consensus, and consul can expose services through special "fake dns zones", in this case that host will always resolve to the primary swarm manager and I want TLS to work correctly with that host name as well as the actual IPs and hostnames of each docker engine.

* Use `docker save` to save the above containers as tar balls that you can prep undockerized hosts with (how you get the tarballs there is up to you).

* On each new host, install docker then use `docker load` to load the above images.  Then (assuming these image names are `bootstrap:docker` and `bootstrap:swarm`):

    ```bash
    FQDN=$(hostname --fqdn) docker run --rm -t \
                         -e IPADDRESS=$(gethostip -d $FQDN) \
                         -e HOSTNAME=$FQDN -v /etc/docker:/etc/docker bootstrap:docker
    FQDN=$(hostname--fqdn) docker run --rm -t \
                         -e IPADDRESS=$(gethostip -d $FQDN) \
                         -e HOSTNAME=$FQDN -v /etc/docker:/etc/docker bootstrap:swarm
    ```

* Start docker. If you are running swarm manger in a container you can use use `-v /etc/docker:/etc/docker:ro` to mount the certs & keys read-only into the container and then pass `--tlsverify --tlscert /etc/docker/swarm.pem --tlskey /etc/docker/swarm-key.pem --tlscacert /etc/docker/ca.pem` to your `swarm manage` command.

As in all things, HTH, YMMV and HAND.

**Comment by ArmandGrillet** [comment]
Thanks a lot for your extensive explanation! It doesn't work, when launching `swarm manage` it returns:
```zsh
time="2015-07-06T09:51:54Z" level=info msg="Listening for HTTP" addr=":2375" proto=tcp 
time="2015-07-06T09:51:54Z" level=error msg="Get https://192.168.42.22:2375/v1.15/info: dial tcp 192.168.42.22:2375: connection refused" 
time="2015-07-06T09:51:54Z" level=error msg="Get https://192.168.42.22:2376/v1.15/info: dial tcp 192.168.42.22:2376: connection refused" 
```
The weird thing is that I don't have launch `swarm join` on the node but it returns me this message! I removed all my containers on both the `master` and the `node` and tried again and it still returns me these messages.

**Comment by aanm** [comment]
@ArmandGrillet Be aware that it's a different error, I would assume that either:
 * Ports 2375 and 2376 aren't open on 192.168.42.22's firewall
 * Master can't reach 192.168.42.22

Did you try it without your using your TLS config?

**Comment by ArmandGrillet** [comment]
Yes it's working perfectly without TLS using the port 2375.

**Comment by abronan** [comment]
@ArmandGrillet Any luck on getting this to work? (hoping that the comments above helped you in the meantime, this one is long standing)

Looking back at it, I think this was a legitimate connection issue due to the VM setup and certs generated. An `Handshake failure` is usually a symptom of an issue with the certificates. In this case, this might be an issue with IP SAN as you didn't use `/CN` on your machine thus one side dropping the connection because the certificate is considered as not valid.

Feel free to close this if this was solved in the meantime.

**Comment by ArmandGrillet** [comment]
My internship tutor has published [a procedure to use Swarm over TLS two months ago](https://github.com/disastrous-charly/swarm-is-easy) using the same configuration as me and it's working. Thanks for your comment, I'm closing the issue now.

**Comment by abronan** [comment]
@ArmandGrillet Nice! Thanks you for the update.

/cc @moxiegirl WDYT about having a page in the docs referencing links to blog posts and useful resources such as the one linked above? This would be useful to get started with Swarm and especially to setup TLS, which is a point of struggle in the docs.

**Comment by moxiegirl** [comment]
@abronan I think that is a great idea. We will put that on the todo list.
