### ISSUE TITLE
"Oversized record" error on Microsoft Azure trying to get swarm info

### ISSUE THREAD

**Issue by mpilant** [docker/swarm#1096]
I'm trying to remotely get the swarm manage information using the command:
    docker --tls -H tcp://thesystem.cloudapp.net:2375 info
This command fails with an "oversized record received with length 20527".
The local system is Ubuntu 14.04 LTS running the docker 1.71 client.  The (Azure VM with the Docker VM extension) remote system is also Ubuntu 14.04 LTS reporting version 1.7.1 for the client and server.
The docker daemon is running, and the swarm container is also running.  (If I run the info command on the VM, it succeeds but report no nodes; #1095, separate issue, but at least the command runs.)
Any suggestions?
- Mark

**Comment by abronan** [comment]
Hi @mpilant, it looks like you didn't set up TLS correctly on your Swarm Agents and your Manager.  Docker uses port `2376` for SSL so make sure that your Swarm agents have their docker daemons properly configured for secure communication (The docker documentation has an extensive part on configuring the daemon to use SSL). There are also a lot of resources to configure Swarm with TLS.

If you still have trouble have trouble running Swarm with TLS, you can still use `docker-machine` (that does all this configuration for you) and follow the documentation to setup your Swarm.

**Comment by mpilant** [comment]
Hi @abronan .  At the moment, I have Docker configured to use TLS, and I can it to remotely interact with the individual nodes without any problems.  So I believe it is configured properly.  The problems seem to be with trying to set up a swarm.  This is one area where the documentation I have found (from Docker, Microsoft, etc.) is really pretty poor.  Almost all is really good at describing the commands to use not not very good at describing what the arguments and options of the command are given and what they are supposed to do.
I've avoided docker-machine, and am doing the steps manually, because I really want to understand what is going on.

**Comment by abronan** [comment]
Thanks for the info,

> This is one area where the documentation I have found (from Docker, Microsoft, etc.) is really pretty poor

Yes! Our documentation is pretty poor on this side but we expect to make it evolve soon enough to explain how to setup everything manually.

Regarding your issue, it's hard to pinpoint what might be problematic but this is definitely your Manager that cannot contact your Swarm Agents due to TLS configuration. The set of commands to get it working is non trivial so not sure at which point and on whose side (daemons/Manager) the setup is faulty. Would help if you can try again (also using port `2376` instead of `2375`) and followup here if you still have the issue with the process and commands you are using.

**Comment by ahmetalpbalkan** [comment]
@mpilant we are working on amln Azure Resource Manager Template that would allow you to create swarm clusters with one click and we're hoping to write tutorials / shoot videos about it... Sorry fo the confusion in this area, this is all new cutting edge tech and I also agree we don't have very comprehensive docs at this area. In fact Azure docs were written quite a long time ago when Swarm first came out, they might not even be remotely valid today.

**Comment by mpilant** [comment]
@abronan Regarding port usage, could you help me understand the (port) relationship of "plain" Docker with swarm?  From what I can see from the documentation, for "plain" docker, port 2376 should be used when secure (TLS) communications are needed and 2375 should be used when security is not a concern.  Is this correct?

Now for swarm.  It would seem to make sense two ports would be needed: one for docker, and one for swarm management.  From what I can understand, it appears the 2375/2376 is used for Docker, and a another port, specified on the Docker run command for "swarm manage" is used for swarm management.  Does this include communications with the swarm agent on the swarm nodes?

The final question is if there is a problem using the non-secure 2375 for the swarm manager port?

As you can see there is a lot of room for improvement in the documentation of how the ports are used and if particular ports have special/unique meaning.

Thanks in advance.

**Comment by mpilant** [comment]
@ahmetalpbalkan Templates are nice, but do little to help understand what is really going on; unless accompanied by good documentation.  Understand what is really going on is very useful when something goes wrong; you have a better idea of where to start looking.

**Comment by abronan** [comment]
@mpilant 

> From what I can see from the documentation, for "plain" docker, port 2376 should be used when secure (TLS) communications are needed and 2375 should be used when security is not a concern. Is this correct?

Yes. 

For the Swarm Manager, it is configured in both Client and Server mode because it acts both as a client (communication with remote docker daemons) and a daemon (to serve requests from docker cli clients or other docker API compatible libraries). The port of the Manager is specified (no real convention here) when you first run it with:

`swarm manage -H :4000 [...] <cert-flags> <discovery>`

This gives us:

```                       
                            Docker CLI
                                +   
                                |     
                                |        
                                | 4000 (or else)    
                                | server
                       +--------v---------+   
                       |                  |          
          +------------>   Swarm Manager  <------------+     
          |            |                  |            |    
          |            +--------^---------+            |  
          |                     |                      |     
          |                     |                      |  
          |                     |                      |     
          |                     |                      |  
          | client              | client               | client  
          | 2376                | 2376                 | 2376   
          |                     |                      |      
+---------v-------+    +--------v--------+    +--------v--------+     
|                 |    |                 |    |                 |    
|   Swarm Agent   |    |   Swarm Agent   |    |   Swarm Agent   |    
|     Docker      |    |     Docker      |    |     Docker      |       
|     Daemon      |    |     Daemon      |    |     Daemon      |  
|                 |    |                 |    |                 |          
+-----------------+    +-----------------+    +-----------------+    
```

> The final question is if there is a problem using the non-secure 2375 for the swarm manager port?

`2376` is the default SSL port for the docker engine but you can setup the Swarm Manager to use `2375`, as long as you have all the proper flags set for secured communication. I'd suggest using the same conventions though but you are free to pick a meaningful port for the Manager.

Hope this makes more sense, let us know if you still run into trouble running swarm with TLS. There are a lot of resources out there to help you (see #341 for example).

**Comment by mpilant** [comment]
I suspect this problem may be related to the problem in #1095, which was "fixed" by using a different Azure subscription.  As this is not the first time this has happened to me (the last time was with Azure and IoT), I expect there are some subtle differences between Azure subscriptions.  All I have to do is find out what they are.

**Comment by ahmetalpbalkan** [comment]
@mpilant I heavily doubt that there's a difference. All these stuff run in userspace (i.e. your VM) and Azure subscription is just a logical unit in Azure backend to categorize billing of resources under a payment method. I believe

> oversized record received with length 20527

means you're probably trying to access a non-TLS endpoint using TLS auth (or vice versa) due to misconfiguration in the Docker engines which run on each VM or the Swarm manager(s). You are not using any Azure-specific services or configurations in this case.
