### ISSUE TITLE
Is it possible to use Azure Load Balancing with a Docker Swarm?

### ISSUE THREAD

**Issue by mpilant** [docker/swarm#1122]
For about the past month, I've been trying to determine whether or not is it possible to use Azure (Internal) Load balancing with a Docker Swarm.  My testing indicates it is possible to use Azure Load balancing with a collection of VMs running Docker container applications.  It also indicates it is possible to create a Docker Swarm on Azure (using either Docker Machine or the Azure CLI), but the swarm created is non-functioning / broken (#1095).  To date, however, I have not been able to get swarm and load balancing working together.
Assuming an operational Docker Swarm, this leads to the question: Is it possible to create a docker swarm, whose containerized applications can operate behind Azure Load Balancing.

**Comment by ahmetalpbalkan** [comment]
@mpilant yes it is possible. The template we have at https://github.com/Azure/azure-quickstart-templates/tree/master/docker-swarm-cluster does that. (It's currently broken as there was a leadership election bug that's fixed in swarm-0.4-rc2, I need to update the template.)

This template pulls all managers behind an Azure Load Balancer (so that you can just manage the cluster from a single endpoint like `tcp://ahmetswarm-manage.westus.cloudapp.azure.com:2376`) and it creates a separate  LB for slave nodes (which you need to deploy your containers on static ports such as `-p 80:80` and then create LB rules for those services on the LB using the Azure portal etc.). We also give a public DNS name / IP address for the Load Balancer of the slaves.

Please read the README here: https://github.com/Azure/azure-quickstart-templates/tree/master/docker-swarm-cluster and ping me on such issues as Swarm is not an Azure support channel and I just came across this question by chance. :)

**Comment by mpilant** [comment]
Is there any documentation / description of just what the template is doing?  That would greatly help understand just what is going on, and what to do should it be necessary to do a (slightly) different configuration.

**Comment by ahmetalpbalkan** [comment]
@mpilant you can refer to the readme link above, also the template language itself is not very complicated and it is pretty much self-documenting. I suggest going through readme first and then once you get an idea you can jump into specifics by looking at the azuredeploy.json.

**Comment by rgardler** [comment]
Another way of figuring out what is happening in that template is to deploy it and then use https://resources.azure.com/ to look at what happened (there is a documentation tab which explains the parameters you see). 

For a 5 minute intro to this excellent tool take a look at https://www.youtube.com/watch?v=Ye9eOYRK3jE

**Comment by anweiss** [comment]
Not sure if this is related or if the issue has regressed...but using this template, I noticed that if I have a container already running and I try to add a new Probe and Load Balancing Rule mapped to the container's exposed ports, the container unexpectedly exits while the Azure Load Balancer is updating.

**Comment by rgardler** [comment]
What do the container logs say about the reason for exiting. I con't see how the LB can be responsible for this unless it's a bug in the code in the container.

**Comment by ahmetalpbalkan** [comment]
@anweiss yes please, can you send the `docker logs` for the container as well as docker-engine logs (`journalctl -u docker`) from the VM? 

Note to repo owners: This issue is not appropriate for docker/swarm repo, you can close anytime.

**Comment by anweiss** [comment]
@ahmetalpbalkan sent...following up offline...feel free to close this issue. thanks

**Comment by harneet463** [comment]
Mapping the port using the -p option would limit the container to single instance on a worker.
If we do not use -p load balancer will not work.
Is this correct or am I wrong ?

**Comment by dahovey** [comment]
I ran into issue with Docker Swarm behind Azure LB. My issue was simple configuration issue with Health Probe for LB. Default type of probe is TCP not HTTP. After switching probe type in LB to HTTP load balancing to swarm cluster works great.

Hope this helps someone.
