### ISSUE TITLE
Manager does not retry for failed nodes (token:// discovery)

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/swarm#1185]
version: 0.4.0

When Swarm manager starts (using discovery `token://`), if the node in the list is down, the manager flags it as dead **indefinitely** and does not pick it up again when the node comes afterwards.

This also happens after the Swarm manager was started. Once a node dies, the engine logs `Removed engine %s` and even though engine comes up afterwards, in the `--debug` logs the only `Updated engine state` belongs to the node that never failed.

Some logs... Around 05:36:20 I took node `alp` down and brought up 2 minutes later. But it never showed up in the logs nor in the `/info`... But when I started another manager container that targets the same token://, it was able to pick up the node died earlier. 

Hence, the manager is most definitely not retrying for failed nodes. It should be more tolerant to faults.

```
time="2015-09-01T05:36:15Z" level=debug msg="Updated engine state" id="VJEO:U3TS:HJ7T:IKNS:JHJP:YTOW:UVLP:NUMC:RSA7:U42X:OMNC:QCYW" name=hellodocker
time="2015-09-01T05:36:16Z" level=info msg="Registered Engine hellodocker at hellodocker.REDACTED:xxxx"
time="2015-09-01T05:36:16Z" level=debug msg="Updated engine state" id="2MJA:DPJM:6ACB:GUN2:G4VK:GZRT:NNMS:JUYJ:IEYB:A5AP:HAMX:XCDA" name=alp
time="2015-09-01T05:36:16Z" level=info msg="Registered Engine alp at alp.co:xxxx"
time="2015-09-01T05:36:34Z" level=info msg="Removed Engine alp"
time="2015-09-01T05:36:46Z" level=debug msg="Updated engine state" id="VJEO:U3TS:HJ7T:IKNS:JHJP:YTOW:UVLP:NUMC:RSA7:U42X:OMNC:QCYW" name=hellodocker
time="2015-09-01T05:37:16Z" level=debug msg="Updated engine state" id="VJEO:U3TS:HJ7T:IKNS:JHJP:YTOW:UVLP:NUMC:RSA7:U42X:OMNC:QCYW" name=hellodocker
time="2015-09-01T05:37:46Z" level=debug msg="Updated engine state" id="VJEO:U3TS:HJ7T:IKNS:JHJP:YTOW:UVLP:NUMC:RSA7:U42X:OMNC:QCYW" name=hellodocker
time="2015-09-01T05:38:16Z" level=debug msg="Updated engine state" id="VJEO:U3TS:HJ7T:IKNS:JHJP:YTOW:UVLP:NUMC:RSA7:U42X:OMNC:QCYW" name=hellodocker
time="2015-09-01T05:38:46Z" level=debug msg="Updated engine state" id="VJEO:U3TS:HJ7T:IKNS:JHJP:YTOW:UVLP:NUMC:RSA7:U42X:OMNC:QCYW" name=hellodocker
time="2015-09-01T05:39:16Z" level=debug msg="Updated engine state" id="VJEO:U3TS:HJ7T:IKNS:JHJP:YTOW:UVLP:NUMC:RSA7:U42X:OMNC:QCYW" name=hellodocker
time="2015-09-01T05:39:47Z" level=debug msg="Updated engine state" id="VJEO:U3TS:HJ7T:IKNS:JHJP:YTOW:UVLP:NUMC:RSA7:U42X:OMNC:QCYW" name=hellodocker
time="2015-09-01T05:40:17Z" level=debug msg="Updated engine state" id="VJEO:U3TS:HJ7T:IKNS:JHJP:YTOW:UVLP:NUMC:RSA7:U42X:OMNC:QCYW" name=hellodocker
time="2015-09-01T05:40:47Z" level=debug msg="Updated engine state" id="VJEO:U3TS:HJ7T:IKNS:JHJP:YTOW:UVLP:NUMC:RSA7:U42X:OMNC:QCYW" name=hellodocker
```

cc: @garimakhulbe

**Comment by MHBauer** [comment]
I can confirm the behavior, though I don't see the "removed engine" message.

I could make an argument that this would self correct in most instances. However it would be better off to not have any timing dependent problems.

**Comment by ahmetalpbalkan** [comment]
@MHBauer maybe you need to start with `--debug` (actually it's an `info` log, but I'm not sure)...
and no it doesn't self-correct (unless container/VM restarts), that's what this issue is about.

**Comment by MHBauer** [comment]
It self corrects if the node stops advertising long enough for it to be removed from the list, and then re-added afterwards.

Here's my version info:
```
root@node-1:~# docker -H 127.0.0.1:3375 version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/0.4.0
 API version:  1.16
 Go version:   go1.4.2
 Git commit:   d647d82
 Built:
 OS/Arch:      linux/amd64
```

**Comment by MHBauer** [comment]
When the engines are bulk added in https://github.com/docker/swarm/blob/master/cluster/swarm/cluster.go#L253 addEngine() fails and returns an error, which is silently discarded. Thus the code never gets to the refresh loop that periodically checks on the state of a node. 

It never gets re-added until it disappears and is readded through the join registration being killed and restarted.

I am not really sure how to fix it, but that is the root cause.

**Comment by ahmetalpbalkan** [comment]
:+1: thanks for the investigation @MHBauer.

**Comment by MHBauer** [comment]
I think this is the same as issue #1044. We don't try to do an initial connect to an engine more than once.

**Comment by ahmetalpbalkan** [comment]
eh that seems stalled.

**Comment by aluzzardi** [comment]
We have to redesign the node registration system.

Right now, as you mentioned, if the initial registration fails then it gives up. That's for multiple somewhat valid reasons.

It just assumed that whenever we detect a new node, a join was just issued therefore the node has just been started therefore it should be reachable. If not, then it was probably because of a join misconfiguration.

Adding a misconfiguring node to the cluster would have caused issues and that's why it's the way it is.

Things changed however, and it should probably work like this instead:

- Whenever we find an engine in discovery, we ALWAYS add it
- The codebase just have to deal with the fact that we might have invalid engines in the cluster
- Engine will retry to connect to it using the delayer (random interval)
- `docker info` would report non-connected nodes as well, along with the last error message. This way, you would actually see in `docker info` why we couldn't reach an unresolvable address for instance

**Comment by ahmetalpbalkan** [comment]
@aluzzardi ^ this SGTM, I think for point 4, as long as we list healthy / non-healthy engines separately in the output, it can be a very clean solution to the problem.

**Comment by aluzzardi** [comment]
Issue now tracked by the node management proposal (#1486)
