### ISSUE TITLE
Support volume API

### ISSUE THREAD

**Issue by bfirsh** [docker/swarm#1189]
Engine 1.9 will have a new volumes API, which Swarm should probably support in some way. It is perhaps not practical to support local volumes, but it could be pretty interesting to support network storage with volume drivers.

https://github.com/docker/docker/pull/14242

/cc @cpuguy83 @lukemarsden

**Comment by lukemarsden** [comment]
Hey @bfirsh - thanks for the ping! @vieux could we do a hangout to discuss what you have in mind for this, and how it can fit into the volume plugins model?

**Comment by vieux** [comment]
@lukemarsden let's keep the discussion here, so it's open to everyone who wants to participate.

**Comment by vieux** [comment]
What do you think of this naive approche to start with, we do the same thing as we do with images.

`GET /volumes`: we do kind of like images, we display volumes for all the machines, without duplication (like https://github.com/docker/swarm/pull/1166)
`GET /volumes/{name:.*}`: we forward to *a* node that has the volume and return the volume (like inspect for images)
`POST /volumes`: we do it on every node, like for pull
`DELETE /volumes/{name:.*}`: we do it on every node, like rmi

**Comment by thaJeztah** [comment]
> POST /volumes: we do it on every node, like for pull
> DELETE /volumes/{name:.*}: we do it on every node, like rmi

One thing to take into account here is that reference counting is performed *per daemon*; What if a plugin offers centralized storage (I.e,, "volume A" on each node actually points to the *same* volume), and that volume is no longer referenced on a node? In that case, the daemon on *that* node will proceed, and remove/delete the volume, whereas it can still be referenced on *another* node.

I also raised this issue that may need some attention in this respect; https://github.com/docker/docker/issues/15997

**Comment by myechuri** [comment]
```
 GET /volumes: we do kind of like images, we display volumes for all the machines, without duplication (like #1166)
GET /volumes/{name:.*}: we forward to a node that has the volume and return the volume (like inspect for images)
POST /volumes: we do it on every node, like for pull
DELETE /volumes/{name:.*}: we do it on every node, like rmi
```

This sounds like duplication of a lot of work done in Flocker. Instead of Swarm reimplementing volume driver's control service functionality, would it be more efficient to make these Swarm calls passthrough to volume driver's control service (like Flocker control service), since the volume driver has greater visibility into backend types (shared/DAS/etc)), therefore dealing with scenarios like @thaJeztah outlined correctly?

Thanks!

**Comment by vieux** [comment]
I would like to be able to use https://github.com/vieux/docker-volume-sshfs with swarm or any other simple volume plugin. That's why I think the work should be done in swarm, not always delegated to the plugin.

**Comment by jimmyxian** [comment]
>POST /volumes: we do it on every node, like for pull

I think do `volume create` on every node is not proper. This case:
Swarm cluster have four nodes. Two nodes have A volume plugin driver, another two have B volume plugin driver. I want use A drvier to craete volumes, just like this:
```
docker -H <swarm> volume create --driver A
```
In swarm, I think we should just do `create` on the nodes that have A volume driver.
But it seems that can not get volume driver list from a docker engine. If we can get volume driver list from a docker engine. In swarm, we can easy find the nodes for `volume create`.

**Comment by thaJeztah** [comment]
@jimmyxian good point; I think you should open an issue for that. As a workaround, daemon labels could be (mis)used to indicate which drivers are supported on a node

**Comment by chanwit** [comment]
@jimmyxian maybe `volume create --filter driver=A`?
If we can support filtering like this, `--filter` could be also applied for `volume ls` too?

**Comment by thaJeztah** [comment]
I think the driver should only be of concern when *creating* a volume (with a specific driver); after the volume is created, the volume can be referenced by its name, and Swarm should only be interested if a volume with that name is present or not. Querying if a volume with a specific name *and driver* exists would take away the abstraction that "named volumes" provide.

It would become "interesting" though, if (for example) "volumeA" exists on two nodes, but created with different drivers.

**Comment by jimmyxian** [comment]
@thaJeztah Thanks. I will create a issue in docker.

@chanwit I agree with @thaJeztah :)
>I think the driver should only be of concern when creating a volume (with a specific driver); after the volume is created, the volume can be referenced by its name

**Comment by lukemarsden** [comment]
Hey @vieux, (@cpuguy83 FYI),

We've done some analysis on your proposed behavior against Flocker plugin's behavior, and it should all work as you propose. Detailed analysis below.

It's important to note that with Flocker and the Flocker Docker plugin, Docker volumes are more like *references* to Flocker volumes. Flocker volumes have a lifetime which can survive beyond that of individual containers and container hosts. With that in mind:

> `GET /volumes`: we do kind of like images, we display volumes for all the machines, without duplication (like #1166)

This will list all references to Flocker volumes that have been created using the Flocker Docker plugin on hosts that are still reachable. It won't list *all* Flocker volumes (there could be Flocker volumes created out-of-band, for example, or on a node which failed and is no longer in the swarm). As long as we're OK with that, this will work. If you do want to be able to see Flocker volumes which never had a Docker volume reference set up to point at it, we'd need to talk about adding a plugin mechanism to Swarm so that it can talk directly to the [Flocker Control Service](https://docs.clusterhq.com/en/latest/introduction/index.html#flocker-basics)'s [Datasets API](https://docs.clusterhq.com/en/latest/reference/api.html#dataset-api-endpoints), which we could do, but it sounds like you want to stick to just aggregating information from the Docker hosts at the moment. Also, the Docker hosts don't ask the backend for a list of volumes either. So they (and therefore Swarm) can only know about volumes that were created through Docker. This is fine for us -- it will work well enough that people can use Flocker and Swarm together, that's the important thing.

> `GET /volumes/{name:.*}`: we forward to a node that has the volume and return the volume (like inspect for images)

That's fine, except an optimization might be to forward to a node which has the volume and currently has a container which is using it. Otherwise the `Mountpoint` response might be null (because there's no guarantee that a Flocker volume is actually mounted on a host just because there's a Docker volume created on it). But maybe consumers of the Swarm API don't care about the `Mountpoint` value anyway, because it's specific to a host.

> `POST /volumes`: we do it on every node, like for pull

Given that Flocker volumes only manifest on one host at a time, initially this seemed like surprising behavior, but after some consideration we realised this should be fine. The Flocker Docker plugin will ensure that names given are unique across datasets across hosts, meaning that if one swarm master tells 10 docker hosts to create 10 docker volumes with the name `foo`, the first one to reach the flocker control service will create the flocker volume and mount it on that host, and (because we are careful to avoid race conditions) the 9 other requests will observe that the volume already exists in the configuration but that's OK - the Docker volumes will still get set up to refer to that dataset from all hosts.

An alternative implementation might be to pick a node at random and create the volume there. That should work just as well for us, but there may be other use cases you have in mind which make the former preferable.

> `DELETE /volumes/{name:.*}`: we do it on every node, like rmi

Delete is a no-op for us at the moment, so that's fine too.

Let us know as soon as you have a prototype of this and we can test it. Eventually we'll aim to set up some integration tests on our CI system to ensure that the analysis above holds up in practice and continues to hold up as Flocker and Swarm both continue to evolve.

Thanks!

**Comment by lukemarsden** [comment]
@vieux @cpuguy83 

You'll be pleased to know that @stephenitis and I tested this and it appears to work as predicted by the analysis above.

Sorry for the long lead time on getting this feedback to you!

**Comment by erikh** [comment]
so, the teardown of `docker volume run` should tear down the volume as well; it currently does not. is there a reason for this? I'm testing with github.com/contiv/volplugin and seeing htis behavior when tearing down containers using ceph volumes; if the signal is not received to remove the mount, the ceph volume lingers there and is unable to be mounted elsewhere safely. I don't know how to resolve this with the current swarm. Please let me know if there's some more information I can provide.

**Comment by moxiegirl** [comment]
@vieux You ok with adding `area/docs` too as this has considerable documentation impact

**Comment by vieux** [comment]
basic volume API was added in swarm, see tests in https://github.com/docker/swarm/blob/master/test/integration/api/volume.bats
