### ISSUE TITLE
Can't create a swarm cluster manually

### ISSUE THREAD

**Issue by kacole2** [docker/swarm#1323]
Been banging my head against a wall for a few hours now. We are looking to use the latest versions of the docker engine, compose, and swarm. 

I create 2 hosts with Docker Machine and set the `--engine-install-url https://experimental.docker.com` (we are creating a lab environment for people to install Swarm manually, thus not configuring via Docker Machine) and the install completes.

on node 1:
```
$ docker pull swarm:1.0.0-rc1
$ docker run --rm swarm:1.0.0-rc1 create
$ docker run -d --restart=always --name swarm-agent swarm:1.0.0-rc1 join --advertise <node1IP>:2375 token://<token from create>
$ docker run -d --restart=always --name swarm-agent-master -p 3375:3375 -v /etc/docker:/etc/docker swarm:1.0.0-rc1 manage -H tcp://0.0.0.0:3375 token://<token from create>
```

on node 2:
```
$ docker pull swarm:1.0.0-rc1
$ docker run -d --restart=always --name swarm-agent swarm:1.0.0-rc1 join --advertise <node2IP>:2375 token://<token from create>
```

you would think that would work. when I'm on node 1 I point the engine to swarm and it's not gathering any data:
```
node1:~$ docker -H tcp://0.0.0.0:3375 info
Containers: 0
Images: 0
Role: primary
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Nodes: 0
CPUs: 0
Total Memory: 0 B
Name: e7bf35cf41fd
```

any ideas? TIA

**Comment by abronan** [comment]
Hi @kacole2,

Could you please output the logs of the swarm Manager (`docker logs swarm-agent-master`)? Either this is a connectivity issue between the swarm Manager and the Agents (are the docker daemons exposed over TCP? with `-H tcp://0.0.0.0:237[5-6]`?), or a discovery issue. Thanks!

**Comment by kacole2** [comment]
@abronan thanks for the response. here are the logs:
```
node1:~$ docker logs swarm-agent-master
time="2015-10-21T19:44:58Z" level=info msg="Listening for HTTP" addr="0.0.0.0:3375" proto=tcp
time="2015-10-21T19:45:18Z" level=error msg="Get http://<node1IP>:2375/v1.15/info: dial tcp <node1IP>:2375: connection refused"
```

no idea if the daemon is exposed over TCP. It was just installed from Docker Machine provisioning

**Comment by abronan** [comment]
@kacole2 If using docker-machine to provision the docker daemons, then they are most likely exposed on `2376` using TLS which explains why the Manager can't connect to the Agents as it is not configured to use TLS (also because the port given to join: `2375`, seems wrong in this case).

As you are setting up the swarm Manager manually (not letting docker-machine set up Swarm for you as explained [here](https://github.com/docker/swarm/blob/master/docs/install-w-machine.md)), you need to configure the Manager to use TLS with `--tlsverify --tlscacert=<CACERT> --tlscert=<CERT> --tlskey=<KEY>` (see this [docs](https://github.com/docker/swarm/blob/master/docs/install-manual.md))

You can also refer to the [Docker documentation](https://docs.docker.com/articles/https/) to setup the daemons manually using TLS not going through docker-machine.

**Comment by kacole2** [comment]
I just tried running these commands on a new host and still no go:
```
$ sudo docker -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock -d &
```

**Comment by kacole2** [comment]
@abronan i'll dig into it more. thanks for the help.

**Comment by abronan** [comment]
@kacole2 Feel free to re-open and comment here if you have any more trouble or question, if you follow the guidelines for the manual install you should be good to go :)

Concerning the TLS part it's a little bit more tricky but following the docker docs that I linked in my comment above you should also be good to go.

**Comment by kacole2** [comment]
@abronan i'm realizing that it won't really work if i'm deploying the hosts with Docker Machine. would probably only work if i start everything from scratch.
