### ISSUE TITLE
Whats command to configure docker to run under SSL?

### ISSUE THREAD

**Issue by bluishpe** [docker/swarm#1429]
Hello,
      Can you point me to documentation that has steps to configure docker under SSL on Linux?

Regards,
Baltazar Luis

**Comment by jimmyxian** [comment]
@bluishpe 
Maybe you can follow this. Hope it helps you.
http://www.blackfinsecurity.com/docker-swarm-with-tls-authentication/

**Comment by abronan** [comment]
@bluishpe There is unfortunately no documentation to set up TLS (because this is a per user/use case scenario) but a lot of good resources. Docker documentation includes instructions to protect the Engine daemon (see the [docker documentation](https://docs.docker.com/engine/articles/https/)).

The resource linked above is also a good one to setup Swarm to use TLS if using as a development or testing environment.

**Comment by abronan** [comment]
Hey @bluishpe, closing this issue as the resources linked above should easily get you started on how to setup Docker with TLS :)

Feel free to comment on this one if you have any more questions or open a new issue if you run into any trouble.
