### ISSUE TITLE
docs: how to write and use a custom discovery backend?

### ISSUE THREAD

**Issue by Kosta-Github** [docker/swarm#1457]
I am somehow missing the information about *all* the necessary steps to take for creating a custom `discovery backend`.

I already found the info about what [interface to implement](https://github.com/docker/swarm/tree/master/discovery#contributing-a-new-discovery-backend), but I am missing the info where to put the generated `backend binary` so that it could be used/picked up by `swarm`, e.g., when using `machine` by:
```
docker-machine create --driver ... --swarm ???
```
May guess is, that I need to create my own `swarm image` derived from the original `swarm image` and place the additional `backend binary` into it at a specific folder (where?), but some step-by-step info would be really helpful!

**Comment by abronan** [comment]
Hi @Kosta-Github,

Sorry for the confusion, this is now done in [docker/libkv](https://github.com/docker/libkv), the interface to implement is mentioned with some other details and examples.

Also you might want to start the backend with its own image rather than bundled with the swarm binary (one process per container). You can then point to the discovery specifying the host IP and exposed port of the container running the KV.

For example:

`docker-machine create --driver <...> --swarm <...> --engine-opt="cluster-store=consul://$(docker-machine ip consul-kv):8500"`

What is the specific backend you would like to implement to be used by discovery?

I'll update the docs asap to mention `libkv` as this is a docs issue. Thanks for pointing this out!

**Comment by Kosta-Github** [comment]
Thanks for the infos, I will dig into the details tomorrow.

I want to write my own simple backend, which should communicate with the (home-grown and in-house) cloud infrastructure APIs of my company querying the tags of the running instances and collect swarm-groups from them.

**Comment by aluzzardi** [comment]
@Kosta-Github Hey - unfortunately we do not support plugins, which means you have to put your discovery backend in the `swarm/discovery` package and run a custom built version of swarm

**Comment by Kosta-Github** [comment]
OK, thanks for clarification.

Then I will probably use the existing `consul` backend...
