### ISSUE TITLE
More optimal host selection strategy

### ISSUE THREAD

**Issue by ykumar6** [docker/swarm#149]
How easy or hard would it be to add a strategy where

1) Selection favors data locality on host (image cache)
2) Selection favors least weighted host (each task .. building vs running, assigns different weights to a host)

Here is something we wrote internally.
https://github.com/CodeNow/mavis

We don't have any Go programmers but will try to contribute to this

**Comment by aluzzardi** [comment]
Hey @ykumar6 

We addressed many of this issues since then in our new scheduler (balanced strategies, better filters, etc).

I guess this issue is very generic and it's going to be a constant focus for us to improve the scheduler.

If you want to suggest improvements, please open issues for specific areas.

Thanks!
