### ISSUE TITLE
Question: Swarm Discovery and --cluster-store on Docker engine

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/swarm#1521]
Hi, I have a question. I'm using `consul://<IP>:8500/nodes` in my `swarm join`/`swarm manage` commands.

Should I set the `--cluster-store` on the agent nodes to this exact value to make use of multi-host networking or a different one? I am trying to find out if there would be a reason (such as collisions) to not to do that.

**Comment by abronan** [comment]
`swarm join` is optional now, you can use docker with `--cluster-store/--cluster-advertise` and the additional `--discovery-opt kv.path=docker/nodes` when starting the manager and it will point to the docker discovery.

And no collision, it works just fine :smile: that's what I'm doing as the default now.

Just saw that this is not documented yet though... but that could be confusing for new users (what should I use? `swarm join`? the `docker discovery`? etc.). We might wait for 1.1 because we plan to remove `swarm join` entirely and point to the docker discovery as the default.

**Comment by ahmetalpbalkan** [comment]
@abronan I read somewhere (probably on multi-host networking tutorial) that `swarm join` is going away, it totally slipped from my mind sorry.

I think removing `swarm join` entirely and documenting so is the best option.

**Comment by ahmetalpbalkan** [comment]
Thanks!
