### ISSUE TITLE
--cluster-advertise without 'swarm join': nodes are not discovered

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/swarm#1524]
I have a CoreOS cluster running docker1.9.1 and swarm:1.0.1 (compiled from release).

My docker engines on agent nodes start with:

    docker daemon --host=fd:// -H=0.0.0.0:2375 \
        --cluster-store=consul://10.0.0.4:8500/nodes
        --cluster-advertise=eth0:2375

and I do not run `swarm join` and I start swarm manages with:

    swarm manage --replication [...] consul://10.0.0.4:8500/nodes

Swarm managers come up and elect a leader, however when I query `docker info` on swarm manager, I don't see any nodes and when I run containers I get:

    Error response from daemon: No healthy node available in the cluster

I am not using `--discovery-opt kv.path=/nodes` (as @abronan brought up in #1521) because my `consul://<ip>/<path>` already has `<path>=nodes` in it.

Any ideas?

**Comment by abronan** [comment]
@ahmetalpbalkan You need to use:

```
swarm manage <...> --discovery-opt kv.path=docker/nodes consul://10.0.0.4
```

We didn't wanted to break backward compatibility for existing swarm users by changing the default namespace and docker sets a different namespace for the keys (`docker/nodes` instead of `docker/swarm/nodes`). So using the flag is mandatory in this case to override the default base path.

Also leave out the suffix in the URL `/nodes` or it will also point to the wrong key (it is used as a prefix so this will end up being `nodes/docker/nodes`). I'll flag it as docs and add the relevant steps to make this work as of `1.0.0`. Sorry for the confusion and thanks for pointing this out.

**Comment by ahmetalpbalkan** [comment]
@abronan Hmm thanks a lot for the answer, you're right, I found it quite a bit implicit as well. This fixed my problem, thanks.

**Comment by argon** [comment]
Should this be reopened for tracking as there appears to be no final resolution /cc @abronan

**Comment by abronan** [comment]
Thanks @argon. Yes let's reopen, a new documentation is coming and explaining this point but as of now there is still no clear mention on how to do it.

**Comment by rolfedh** [comment]
@moxiegirl @amitshukla I didn't cover this in topics for 1.10. Mary?
