### ISSUE TITLE
Spread scheduling but counting only running containers.

### ISSUE THREAD

**Issue by ikreymer** [docker/swarm#1541]
I'd like to request a scheduling strategy (unless its possible to do so with current spread scheduling) that counts only running containers rather than all containers on the node.

The issue is that a node may have a bunch of containers that have exited/dead/stuck in created, but few running containers and thus will not receive any more containers. Even though the node is not running as many containers, it will still get a load distributed based on the total rather than the total running number.

(Of course another solution for me is just to clean up not running containers but I thought perhaps this may be useful for others as well)

**Comment by dongluochen** [comment]
@ikreymer We are going with `another solution ... is just to clean up not running containers`. The reason is to be consistent on swarm resource management. Swarm considers mapped network ports, container memory reservation, etc as used resource until the container is deleted. Otherwise restarting the containers would result in conflict/failure. Under the same principal swarm counts stopped containers in container scheduling. #1520 is to update document on this.

**Comment by jimmycmh** [comment]
@dongluochen There is a scenario that cannot delete exisiting container before running a new one. I want to upgrade the image tag of the container from 1.0 to 2.0 and still keep the volumes, so that i have to run a new container with --volume-from in the same host. The problem is, as swarm take the stopped containers into account, that host is filtered out when the old container has a port mapped to the host because the new container wants the same port. How can i solve this?

**Comment by dongluochen** [comment]
@jimmycmh [Data volume container]( https://docs.docker.com/engine/userguide/dockervolumes/) is independent of service and can be attached to multiple containers. Separating data volume from service would resolve your problem. If this is not the issue you have, can you elaborate your use case?

**Comment by jimmycmh** [comment]
@dongluochen thanks for replying. Actually we are providing docker service to our users and we are using docker-compose to update containers when users changing their compose file. The behavior of docker-compose is to start a new container with --voumes-from to the old container, and if there is an binded port to the host, restarting will fail. 
And in spite of docker-compose, it's unconvenient  to get volumes of a container if there's no host directory.

**Comment by dongluochen** [comment]
@jimmycmh If you want volumes to be persist at upgrade, you may define data volume containers without port mapping. In the following example, I can remove web and replace it with another image. `docker-compose up --no-recreate` will not change your data volumes. If it doesn't work for you,  example yml file may be helpful. 

```
data:
    image: busybox
    volumes:
        - "/home/dchen/temp/www:/srv/www"
web:
    image: nginx 
    ports:
        - "443:443"
        - "80:80"
    volumes_from:
        - "data"
web3:
    image: nginx 
    ports:
        - "843:443"
        - "8088:80"
    volumes_from:
        - "data"
```
