### ISSUE TITLE
Proposal: Use docker client library

### ISSUE THREAD

**Issue by jimmyxian** [docker/swarm#1560]
Docker Master code have already extracted a standalone client library(https://github.com/docker/docker/pull/18472) from the cli that can be used outside of docker. I think we should use that library instead of `dockerclient`.

/cc @docker/swarm-maintainers

**Comment by jimmyxian** [comment]
But it does not have `mock` module. It will have a impact on our tests.

**Comment by abronan** [comment]
I think this is the way to go, even though it might be quite tricky as of now.

For example in `dockerclient`, on top of the test mocking issue, we also have the `nopclient` which voids every actions once the Engine goes down. It avoids heavy locking around the engine list/struct and pending operations (it would usually panic rarely on `refresh` because of this). So I'm not sure we can migrate right away before we get the same constructs on the client library on the Engine side.

**Comment by MHBauer** [comment]
Good to have this issue to track.  Give it some time to move to it's final location.

**Comment by nishanttotla** [comment]
Closing this issue since discussion is being tracked in #1879. Please review PR #1880 for a starter implementation of introducing the `engine-api`.

**Comment by jimmyxian** [comment]
@nishanttotla Great!
