### ISSUE TITLE
Proposal: Swarm to use mesos roles as constraints

### ISSUE THREAD

**Issue by Spritekin** [docker/swarm#1591]
While using swarm on mesos, I noticed the swarm filters were always used to pick the nodes. However my cluster has already some role definitions in the mesos slaves.

It would be interesting if Swarm could pick some of the mesos role labels as filters the same way it picks some docker filters (node, storagedriver, executiondriver, kernelversion, operatingsystem). It would make my life so easy instead of having to reconfigure the labels in both mesos AND docker.

**Comment by gradywang** [comment]
@Spritekin  Currently, Swarm register to Mesos with the default role `*`, and it can not register with multiple roles, because Mesos does not support now,  so if you make static reservation for some roles in the Mesos slaves, Swarm will not get those resources except the resources which do not be reserved to any role. So your proposal is depend on the multiple roles support for a framework in Mesos. Right?

**Comment by gradywang** [comment]
#dibs

**Comment by Spritekin** [comment]
I was thinking more on the line that swarm should only accept resources from the groups specified in the filter when launching the container.
But I guess you are correct, this may depend on the multiple role support on mesos.

**Comment by nishanttotla** [comment]
Closing due to https://github.com/docker/swarm/pull/2853
