### ISSUE TITLE
Using a static file describing the cluster

### ISSUE THREAD

**Issue by dingzhengkai** [docker/swarm#1596]
About Discovery service, consider your example in "Using a static file describing the cluster"
```
swarm manage -H tcp://<swarm_ip:swarm_port> file:///tmp/my_cluster
```

I excute the following command to create manage container on my first server, 192.168.40.201:  
```
docker run -p 2222:2375 -v /tmp/my_cluster:/tmp/my_cluster swarm manage -H tcp://192.168.40.201:2222  file:///tmp/my_cluster
```

The /tmp/my_cluster has the swarm-node ip/socket
```
192.168.40.202:2375
192.168.40.203:2375
```

Then i got  error
```
time="2016-01-08T02:47:14Z" level=info msg="Listening for HTTP" addr="192.168.40.201:2222" proto=tcp 
time="2016-01-08T02:47:14Z" level=fatal msg="listen tcp 192.168.40.201:2222: bind: cannot assign requested address"
```
If i remove the -H option, for example
```docker run  -p 2222:2375 -v /tmp/my_cluster:/tmp/my_cluster swarm manage file:///tmp/my_cluster```
Or 
```docker run -p 2222:2375 -v /tmp/my_cluster:/tmp/my_cluster swarm manage -H tcp://0.0.0.0:2375  file:///tmp/my_cluster```
It works . (Why 0.0.0.0)

I just want to know what the -H really mean, how to use ?
And  the swarm command can't excute in bash, but by running a container, right?

Thanks!

**Comment by MHBauer** [comment]
You can run the swarm command directly, outside of the container. We really need to form a consistent opinion on what to show in the docs.

**Comment by MHBauer** [comment]
I am not great with networking, but my read is the 0.0.0.0 let's the program bind to whatever IPaddr is already bound on the interface it uses. For the 192 problem, I think, since it is inside of a docker container, the interface inside the container is already bound. Mine usually ends up bound to a 172 address.

I need someone else to jump in and explain what's really going on.

**Comment by dongluochen** [comment]
`-H` defines docker service endpoint for docker or swarm. In your command, 
```
docker run -p 2222:2375 -v /tmp/my_cluster:/tmp/my_cluster swarm manage -H tcp://192.168.40.201:2222  file:///tmp/my_cluster
``` 
swarm manager tries to bind 192.168.40.201:2222. But swarm was started with `docker run`, i.e., a container created with default network (bridge mode). The container doesn't have its host's IP address. It has a docker0 interface where a private IP is assigned. The bind command fails here because host IP is not available inside the container. 

When you use `-H 0.0.0.0:2375` swarm binds to port 2375 of container interfaces. `-p 2222:2375` creates a port mapping from host:2222 to container:2375. For now requests send to host:2222 will be forwarded to container:2375. So you should add host:2222 to the swarm manager discovery file.

**Comment by dingzhengkai** [comment]
Hi, MHBauer, thank you. ——I don't know  how to run the command outside of the container, and i have not found some docs about that，may you show me where to find that? I refered to the  manually install doc and the disvovery service doc.

**Comment by dingzhengkai** [comment]
And dongluochen, thanks too. 
You mean the -H's value should be a ip for swarm manager(whatever a server or a container ) ?
If so, i can understand that when use docker run to get the swarm manager container up,  the -H should be a ip in the bridged network, for example 172.17.x.x .  But in the 'docker run' way, i  don't know the container's ip, then how to assign the ip?

**Comment by dongluochen** [comment]
@dingzhengkai You don't need to know the docker0 IP address 172.17.x.x. `-H` specifies an access endpoint in IP:port format. In `-H 0.0.0.0:2375` 0.0.0.0 means all IP addresses in the container so swarm  listens on port 2375 of all IP interfaces. What you need is a port mapping by `-p` option that swarm is accessible from external.

**Comment by dingzhengkai** [comment]
@dongluochen I know what you mean ,thanks.
