### ISSUE TITLE
Swarm, network and '--iptables=false'

### ISSUE THREAD

**Issue by wildsurfer** [docker/swarm#1639]
This issue is related to more general one #1623, created by me before.

So I'm in a research of the way to add security layer to my containers in a swarm cluster.

Given
--------

1. Swarm cluster (3 nodes) built with a help of docker-machine
2. 3 containers (`proxy`, `database`, `web`)
3. Docker network feature with overlay driver is used to add ability for containers to communicate across the different nodes

Problem
-----------

I need a way to drop connections from the world to `database` container but leave the ability for `web` container to connect to `database`.

First attempt
----------------

First thing that I was trying to do is installing ufw on each host and trying to add some rules to drop connections from outside. Unfortunately no luck due to fact that docker is overwriting iptables rules to allow access for newly created container from anywhere. Check [this post](http://blog.viktorpetersson.com/post/101707677489/the-dangers-of-ufw-docker)

Second attempt
---------------------

Then I tried to re-start my docker hosts with `--iptables=false` option. This prevents docker from adding any specific iptables rules. This allowed me to drop connections from outside but faced me with another problem. I'm using [docker network](https://docs.docker.com/engine/userguide/networking/dockernetworks/) instead of legacy `--link` and it seems that docker network doesn't play well with `--iptables=false` option.

Any ideas? :)

**Comment by wildsurfer** [comment]
NVM

**Comment by bokysan** [comment]
How did you solve this? I'm facing the same issue?

**Comment by wildsurfer** [comment]
@bokysan Actually text above doesn't makes sense cause I was a bit tired when I was writing it. Actually, docker doesn't allow connections to your container from outside by default.

**Comment by bokysan** [comment]
The following is for reference for anybody googling the same problem:

Weird. My set up was as following:
- block all incoming traffic for 80 & 443 via IPTABLES (INCOMING) on eth0
- have a docker container listening on "25 -> *:25"

My assumption was that nobody would be able to access the container except for local network (eth1). In reality, because of docker's `iptables` fiddling, port 25 was added to the FORWARDING table for all networks and world-accessible.

Tried running with `--iptables=false` which did resolve the issue but swarm agents stopped interconnecting. Presumably because docker's IPTABLES opens up some ports that swarm uses to communicate.

I haven't investigated further and online documentation wasn't very helpful. I ended up using docker with IPTABLES enabled, a container with "25 -> 127.0.1.1:25" and then using balance (https://www.inlab.de/balance.html) and similar tools to actually expose the ports I need.
