### ISSUE TITLE
swarm in spread problem

### ISSUE THREAD

**Issue by yutian1224** [docker/swarm#1648]
docker version: 1.9.1
swarm version: 1.01
nodes1: 25c 64g
nodes2: 25c 64g
nodes3: 42c 128g
nodes4: 42c 128g

I use swarm in spread strategy, but the memory of nodes are different.
The number of containers in node isn't grow up accoring to the specifications.

![image](https://cloud.githubusercontent.com/assets/13673671/12384503/a6081e0a-bded-11e5-912a-2fbe8a65e9c1.png)

**Comment by alu** [comment]
If you need the spread distribute by resource, you have to specify memory limit (by `--memory`) or cpu limit (by `--cpuset-cpus` or `--cpu-shares`). Because swarm can get resource information just at the parameters.

**Comment by yutian1224** [comment]
Thanks.
Is the "--memory-reservation" works too?

**Comment by alu** [comment]
So far, it doesn't work for that.

**Comment by schmunk42** [comment]
I noticed something similar, when images are not pulled beforehand on every node.

**Comment by vieux** [comment]
hi @yutian1224, as @alu explained this is the expected behavior.
If you don't use any CPU (-c) or Memory (-m) resource, swarm is going to simply use the number of containers to spread evenly, that's why the number of containers in the same on every node.

I added a few tests in this PRs https://github.com/docker/swarm/pull/1657 to check that it's working as expected, I added a test were a node has twice as much CPU/Memory as the other once and Swarm places twice as much containers on the bigger node, as expected.

@schmunk42 it it's a private image it's expected since swarm applies an image affinity to make the run succeed (since swarm can pull private images during docker run, only in docker pull)

**Comment by schmunk42** [comment]
@vieux Is there an issue about this to track? I looked around, but found nothing specific; also `docker-compose` related in my case.

**Comment by vieux** [comment]
@schmunk42 since we don't want to store user's credentials in swarm, we nothing much we can do about it :/

**Comment by amitshukla** [comment]
@yutian1224 does the above answer your question?

**Comment by yutian1224** [comment]
yes,thanks for all
