### ISSUE TITLE
Distributed architecture of swarm

### ISSUE THREAD

**Issue by cxxly** [docker/swarm#1659]
Swarm is started with master-slaver architecture which have not a good scalability and  failure tolerance.

![](http://i.imgur.com/e4XtHig.jpg)

Projects like [consul](https://www.consul.io/docs/internals/architecture.html) have a good architecture with  failure tolerance which start multi server and elect a Leader with Raft protocol.

![](http://i.imgur.com/o3zJMmM.jpg)

Can we refactor swarm with this architecture so that it can preform well at scalability and  failure tolerance without deploy HA

**Comment by chanwit** [comment]
@cxxly There's an effort to make this happen in #1198 
Maybe you can help use contributing this. cc @aluzzardi @abronan

**Comment by abronan** [comment]
Thanks for the proposal @cxxly!

@chanwit #1198 is very different I think than what is described in this proposal (because it only concerns discovery). The scope is broader in this one.

Swarm supports High-Availability of the **Manager** though so the first picture is slightly outdated and fault-tolerance is definitely handled.

This requires a non trivial change in architecture for the rest, because you can submit requests to any *Client* in the cluster acting as a Swarm node, so every *Client* in this case is a `Manager` with reduced responsibilities (they don't take scheduling decisions for example).

The notion of `swarm join` (whose only purpose is discovery) and `swarm manage` are a bit blurred to allow for specialized roles instead (`Client` or `Server`).

**Comment by chanwit** [comment]
@abronan I see. Thank for clarifying :):)

**Comment by abronan** [comment]
As you may have already noticed, we created a new repository called [swarmkit](https://github.com/docker/swarmkit) which is really close to the architecture you described and proposed. It indeed improved the scalability and reliability. Closing this one. Thanks!

**Comment by cxxly** [comment]
I have noticed that, Thanks


发自 网易邮箱大师
在2016年07月02日 06:25，Alexandre Beslic 写道:

As you may have already noticed, we created a new repository called swarmkit which is really close to the architecture you described and proposed. It indeed improved the scalability and reliability. Closing this one. Thanks!
