### ISSUE TITLE
Adding network bandwidth knowledge to the schedulers

### ISSUE THREAD

**Issue by chanwit** [docker/swarm#1693]
There is a certain use case that CPU and memory are plenty enough but users would like put a new container in a machine that has lowest bandwidth usage.

Does this make sense?

**Comment by dongluochen** [comment]
We need traffic control support in Engine to limit network usage. AFAIK, this was brought up several times in Engine but has not made any progress, see [docker#16477](https://github.com/docker/docker/issues/16477). The issue is related to docker network model. It sounds doable to me but it may request some work.

**Comment by chanwit** [comment]
@dongluochen I think this is not the case of limiting network usage as currently we have already know some network information from `stat`.

With this we can then choose to put a new container into a node with least network (`rx / tx`) busy.

WDYT?

**Comment by dongluochen** [comment]
@chanwit Docker `stats` has network IO bytes, not bps. It doesn't reflect current bandwidth utilization level. 
```
dchen@vm2:~/go/src/github.com/docker/engine-api$ docker stats --no-stream
CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O               BLOCK I/O
1be29f67b167        0.00%               8.086 MB / 4.145 GB   0.20%               1.039 MB / 8.921 kB   0 B / 8.864 MB
```

That said, I think bandwidth constraint is a legit requirement. Docker doesn't support it yet.

**Comment by chanwit** [comment]
@dongluochen Thanks for that. I maybe use the wrong term :) :)
Like CPU percentage, I think it's worth to implement a scheduler atop this net i/o information away.
Using derivative calculation per second might do the trick.

**Comment by chanwit** [comment]
I'll change it to a proposal then.

**Comment by nishanttotla** [comment]
@chanwit just so things are clear, can you provide more detail about how exactly you will do this calculation?

**Comment by chanwit** [comment]
@nishanttotla would you be interested helping me do math?

I'm thinking of having a separate go-routine collecting network I/O information from each node.
Then having a window, say t=5, to average collected I/O into network usage per second.
I think this will be an enough information to be used by a scheduler.

WDYT?

**Comment by dongluochen** [comment]
@chanwit I'd like to hear your proposal. But I have concerns about its functionality and performance. I'd like to see docker support for bandwidth measurement at container level. A common use case is to limit bandwidth usage on a container so that users can implement traffic management. Averaging bandwidth with a few seconds isn't accurate. The problem is network traffic is not constant. Applications with busty traffic compete for bandwidth and cause packet loss. It wouldn't guarantee low queueing latency or no packet losses for latency sensitive applications. 

The other problem is doing that in manager may cost too much. Collecting data on every container every few seconds is a lot of work on a centralized manager. 

I'd like to hear your use cases and see how we may address them.

**Comment by nishanttotla** [comment]
I agree with @dongluochen. I'm also concerned that the averaging over a really short time period will not be very accurate, and heavily depends on the network. We could increase the averaging period at the cost of efficiency, as long as this feature is made optional with appropriate documentation.

**Comment by chanwit** [comment]
@dongluochen @nishanttotla 
You're right. It seems intensive calculation does not fit inside the manager. Maybe we can have an out-of-process plugin to help feed in some custom information that guides the scheduler?

**Comment by nishanttotla** [comment]
Would it make sense for agents to keep track of this information? And rather than have a short window where we collect I/O information frequently, we could have a large window with less frequent updates. Then the manager could just get this information off of the nodes when (or if) it needs to. Would this be more efficient?

This won't be super accurate all the time, and could give unusable numbers for applications that have peculiar network behavior, but for those we have no other way anyway.

**Comment by dongluochen** [comment]
@nishanttotla I prefer Docker support on traffic management. Out of band metrics and feedback may be heavy solution. 

@thaJeztah @crosbymichael , is there plan on supporting traffic control on Docker Engine? From github, this has been asked several times but I don't find a clear answer, see [docker#16477](https://github.com/docker/docker/issues/16477).

**Comment by amitshukla** [comment]
@thaJeztah @crosbymichael ping ^^

**Comment by thaJeztah** [comment]
I don't think it's actively worked on; as far as I'm aware it was always considered something to control externally? Perhaps @mavenugo knows of plans in this area?

**Comment by shivacherukuri** [comment]
i think i have implemented a solution to limit n/w bandwidth, you can see the following link and send me feedback
https://github.com/shivacherukuri/Docker-Network-Bandwidth
