### ISSUE TITLE
Swarm doesn't list all conflicting constraints when it fails to place a container

### ISSUE THREAD

**Issue by jpetazzo** [docker/swarm#1785]
## What I do

```
docker run -d --name web -p 80:80 nginx
docker run -d --volumes-from web -p 80:80 nginx
```

## What I expect to see

Something telling me that no node can satisfy both constraints "public port 80" and "volumes from web".

## What I see instead

Only the `--volumes-from` constraint is indicated, not the port constraint.
```
docker: Error response from daemon: Unable to find a node fulfilling all dependencies: --volumes-from=web.
```

## Extra notes

FWIW, this is a frequent scenario when mapping host ports with Compose+Swarm (see docker/compose#2866).

If I allocate port 80 on all nodes, then I see the following message:

```
docker: Error response from daemon: unable to find a node with port 80 available.
```

(Which is totally OK because if there are 0 node able to satisfy a single constraint, it's safe to assume that this constraint is the culprit ;-) )

Just for fun, I tried with an affinity constraint, and then I get:

```
docker: Error response from daemon: unable to find a node that satisfies container==6ab2dfe36615ae786ef3fc35d641a260e3ea9663d6e69c5b70ce0ca6cb373c02.
```

I don't know how the constraint engine works, but maybe it could report impossible constraints (for which there are zero node), then conflicting constraints (i.e. when the intersection of nodes for 2 given constraints is empty).

**Comment by nishanttotla** [comment]
@jpetazzo thanks for reporting this, I'll investigate what we could do. My hunch is that for the general case, it could be any subset of issues, so we need to find a way to efficiently get a minimal subset.

**Comment by dnephin** [comment]
If it's not easy to get the incompatible constraints, just listing the entire set of constraints would be a decent improvement. Something like: "unable to find a node that satisfies all of the constraints: container==..., port==80, node==...".

That way at least it's clear the issue was with some combination of constraints, not an individual one, and the full list is easily retrievable from the error message (instead of having to compare the container config against the swarm docs to try and find the combination that failed).

**Comment by jpetazzo** [comment]
Listing all constraints would indeed be an improvement. Especially when using tools like Compose, that add implicit constraints. Thanks a lot!

**Comment by nishanttotla** [comment]
Actually on second thoughts, printing all constraints also seems to be more complex than I thought earlier. If I understood correctly, we'd have to go over all containers to print all constraints which can easily turn out to be a large response (affinities+constraints+dependencies+ports), and potentially expensive also.

@vieux @dongluochen WDYT?

**Comment by dnephin** [comment]
@nishanttotla sorry, I didn't mean all currently active constraints, I meant all constraints required to create the current container. You shouldn't need to look at anything except for the arguments to the API call (or the Container struct if it gets created first).

**Comment by nishanttotla** [comment]
@dnephin okay, my understanding from @jpetazzo's issue was to provide a full set of constraints that together can't succeed, but I get it now.

**Comment by schmunk42** [comment]
I noticed something similar ... let's say I have 2 nodes with label=app and 3 containers in a compose file, all have a constraint `app==1`.

*dummy compose file*
```
service1:
  environment:
    - constraint:app==1
  volumes_from:
    - service2
service2:
  environment:
    - constraint:app==1
service3:
  environment:
    - constraint:app==1
  volumes_from:
    - service2
```

When I run `docker-compose up`, sometimes the following happens:
- service 1 goes to node A
- service 3 goes to node B
- now compose realizes that it can not deploy service2 because of `volumes_from` and fails with something like: "Can not find a node with app==1", which is not really true.

I do not have a reproducible example ready, because it does not happen very often. I tried it last time with `1.1.0-rc2`. But I found it worth adding here.

Btw. does compose/swarm solve all dependencies (like a package manager) before it starts deploying?

**Comment by dnephin** [comment]
@schmunk42 no it does not, but now that we don't need links, and named volumes can replace `volumes_from` there are ways to create a Compose file that don't require the containers to be on the same node.

**Comment by dongluochen** [comment]
For @jpetazzo's initial question, it makes sense to output failure on the full constraint set, not individual one. 

I think it helpful to provide a `dry-run` function. It doesn't run the container but selects nodes that fulfill the constraints. If it cannot find a node, it outputs conflict reason for `every` node. It's a heavy operation but helpful in debugging.

**Comment by schmunk42** [comment]
@dnephin Yeah, I am actually also working on stacks which use the new features, like you described. 
Using a volume plugin is another piece to the puzzle and currently we would be fine with `volumes_from`, but named volumes is the way to go, I think.
