### ISSUE TITLE
Update "Try Swarm at scale" tutorial to use Interlock 1.0.0

### ISSUE THREAD

**Issue by everett-toews** [docker/swarm#1899]
[Version 1.0.0](https://hub.docker.com/r/ehazlett/interlock/tags/) of Interlock just shipped. The [Try Swarm at scale](https://docs.docker.com/swarm/swarm_at_scale/) tutorial uses `ehazlett/interlock:latest`. 

However, from the [README.md](https://github.com/ehazlett/interlock/blob/master/README.md)
>The latest tag (v0.3.3) is the legacy version. That is kept for legacy purposes. It is strongly recommended to use the latest release as legacy is no longer maintained.

The "Try Swarm at scale" example needs to be updated to use `ehazlett/interlock:1.0.0`

**Comment by gittycat** [comment]
Yes please, keep these tutorials and doc up to date.
You guys are the source of truth after all.

**Comment by dongluochen** [comment]
@everett-toews Thanks for bringing up the issue. We will update the doc.

**Comment by dongluochen** [comment]
cc @mgoelzer, @ehazlett. Can you comment on what should change from v0.3.3 to v1.0.0?

**Comment by gittycat** [comment]
@dongluochen The main change is that the new interlock:1.0.0 is now using config data /file instead of flag arguments. You also need to explicitly use "ehazlett/interlock:1.0.0" to pick up this new version. Check other changes here.
https://github.com/ehazlett/interlock/blob/master/docs/getting_started.md

The docker documentation mentions flags, which doesn't work anymore when using v 1.0.0
https://docs.docker.com/swarm/swarm_at_scale/04-deploy-app/#step-4-start-the-voting-application

**Comment by ehazlett** [comment]
As @gittycat said a config file is now required (you can optionally use a KV store).  One other large change is an external proxy container is now required.  For example, the official "nginx" or "haproxy" images from the Docker Hub.  This keeps interlock small and allows for custom proxy images.

**Comment by dongluochen** [comment]
[Try Swarm at scale](https://docs.docker.com/swarm/swarm_at_scale/) has been rewritten and use interlock 1.0.1. See [deploy your infrastructure](
https://docs.docker.com/swarm/swarm_at_scale/deploy-infra/).
