### ISSUE TITLE
Running Conatiners with Docker swarm  using Marathon

### ISSUE THREAD

**Issue by vathanlal** [docker/swarm#1947]
Hi,

I have an environment with Mesos for resource allocation marathon for job scheduling and Docker Swarm integrated with Mesos. My setup is like below

Master Node - Mesos Master and Marathon is running here
Slave 1- Mesos Slave
Slave 2 - Mesos Slave
Slave 3 - Mesos Slave

1st issue

I can use Marathon to start Docker Swarm with Mesos. Its work fine. But the problem is Mesos will automatically schedule the swarm manager to run in one of the slave nodes. I want to run Swarm manger on the Master node. What I need to do?

2nd issue
Right now I can run containers with Docker swarm integrated with Mesos from the command line of the slave in which Swarm manager is running. 

docker -H :4375 run -idt --cpu-shares 1 busybox. 

It is working. But I need to do the same thing using marathon. That is I need to use marathon on the master to run jobs on Docker swarm with Mesos Integration. What I need to do??

**Comment by gradywang** [comment]
@vathanlal, For your first question, if you want to to deploy Swarm Manager on the Master node, you need to also run Mesos Slave on the Master node, then you can use hostname as a constraint on the Marathon Portal to start swarm manager on Manager node.  For your second question, I think it is does not supported now, except Mesos can integrate with Swarm.

**Comment by vathanlal** [comment]
@gradywang Ya that is working for me with mesos slave on the master node. 
Ok that means marathon + Docker Swarm support is not there right now. Right now Docker Swarm can integrate with Mesos only. Thanks.

**Comment by Spritekin** [comment]
a. You may start a slave service in the master and give a special role name for it (i.e. master-slave). In the resources parameter of that master-slave you can specify a number of CPUs and RAM for the master-slave role and nothing for the common role (*). In the marathon job definition for swarm specify you want to use the acceptedResourceRoles=master-slave. That way swarm will be deployed there but nothing else.

That said, is perfectly ok having swarm in a common node. MesosDNS should resolve it so something like swarm.marathon.mesos. Plus if it fails marathon will restart it.

b. I think you are looking at it in the wrong way. There is no way there will be a marathon+swarm integration because there is no need for that integration at all.
Both Marathon and Swarm are frameworks. As such they starts jobs in the slaves using containerizers (mesos or docker). They do not start each other jobs. Your question is like saying I would like swarm to start jobs in marathon.
Of course you can start swarm from marathon, marathon from marathon, swarm from swarm or even marathon from swarm. But you can't start a task from one framework into other framework. 
You can't even start a swarm task from another swarm. Or a marathon task from other marathon framework.
Of course you could hack your way around it. For example, in marathon you can issue a normal command that runs a docker command (docker -H tcp://my.swarm.host run -it http). However this may not integrate well with marathon port assignments so you would need to specify ports manually or force them. I other words... square peg, round hole.

I would recommend you stick with each framework strengths instead of trying to hack your way.

Marathon: Stay-on services that you need running all times. Consider it like init.d or supervisord.
Chronos: Tasks you need to run periodically. Backups, data sync, autoscaling, etc. Consider it cron.
Swarm: One shot tasks, short or long processing tasks. Consider this your command line.

Luck!

**Comment by vathanlal** [comment]
@Spritekin Thanks for the info.. 
right now I have Marathon, Chronos, Aurora and Swarm in my Environment.  Swarm is running in the Mesos Master node itself and I can run containers on Swarm integrated with Mesos from the command line only. I can start Docker Containers from Marathon without using swarm.. 

My Idea is to create a overlay network using Swarm and Submit containers to swarm from Marathon so that each container can access other container in the network. Because I need networking between containers started using Marathon.  Thats why I asked a question like that.. 

Do you have some Idea with ways for creating overlay networks of Docker containers in the Mesos environment?? If you have please share it.. that will be helpful..

**Comment by Spritekin** [comment]
Let me see if I understand. So your problem is that you want to launch new tasks that run using overlay networking. And given Swarm supports overlay (and Marathon doesn't) you want to leverage on that functionality.

Well then you have hit the million dollar question. I'm looking exactly for the same. I think Marathon 1.1.0-rc1 has support for overlay networks on their experimental code (I might be wrong) so you might need to install that first. I haven't had time to try it.

My suggestion is to run a Marathon command and forget all the container stuff. In the marathon command (cmd) write down the docker swarm command as it should run in command line in one of your nodes.

Another way would be to run it using a "launcher" container. Like a small proxy that the only thing it does is to take your args, build a docker swarm command and execute it. So for marathon it is running "launchers".
Marathon >> Launcher >> Swarm >> Container

Never tried that one out though...

Luck!

**Comment by vathanlal** [comment]
@Spritekin Ya exactly the same thing.. Aha Marathon 1.1.0-rc1 has support for overlay networks thats a new info for me thanks.. I will look into that..

**Comment by Spritekin** [comment]
@vathanlal 
Even if its there (again not sure) I would imagine any support will be very thin. I'm not even sure mesos supports it. So I would suggest you hack it using the other suggestions (run as cmd or use a launcher proxy).

**Comment by nishanttotla** [comment]
Closing due to #2853. Please reopen if you wish to continue discussing it.
