### ISSUE TITLE
telling Swarm Manager to listen on a unix socket creates a directory instead of a socket

### ISSUE THREAD

**Issue by nfoonf** [docker/swarm#1991]
starting Docker Swarm with the following config should create a socket **/var/run/swarm.sock**. Instead it creates a directory with this name.

```
docker run --name swarm-manager2 \
--expose=3376 \
-v /var/lib/boot2docker:/var/lib/boot2docker \
-v /var/run/swarm.sock:/var/run/swarm.sock \
-p 3376:3376 \
swarm:latest m --tlsverify \
--tlscacert=/var/lib/boot2docker/ca.pem \
--tlscert=/var/lib/boot2docker/server.pem \
--tlskey=/var/lib/boot2docker/server-key.pem \
-H tcp://0.0.0.0:3376 \
-H unix:///var/run/swarm.sock \
--strategy spread \
--advertise 192.168.99.107:3376 consul://vm4:8500
```

the error Message is:
```
time="2016-03-17T16:10:07Z" level=info msg="Initializing discovery without TLS" 
time="2016-03-17T16:10:07Z" level=info msg="Listening for HTTP" addr="/var/run/swarm.sock" proto=unix 
time="2016-03-17T16:10:07Z" level=fatal msg="is a directory" 
```

docker version: 1.10.2
host: virtual-box

**Comment by dongluochen** [comment]
@nfoonf I guess your intention to start a swarm manager in a container and want the unix socket available on the host machine. In that case you just pass the directory `/var/run` to the container. `swarm.sock` will be created inside the container. Because the directory is mapped, you can access it from host. Skipping other options, it's something like: 

```
ubuntu@manager:~$ docker run -v /var/run:/var/run swarm manage -H unix:///var/run/swarm.sock consul://vm4:8500
```

**Comment by nfoonf** [comment]
Oh I tried what you said. Classical Layer8 Problem :) Thanks for nudging me in the right direction ;-)
