### ISSUE TITLE
Pluggable scheduler API

### ISSUE THREAD

**Issue by tnachen** [docker/swarm#213]
Like to start the discussion around pluggable scheduler API, to make sure it doesn't become impossible to integrate with other schedulers.

I'm coming from the Mesos side, but I'm sure there are others too.

**Comment by bfirsh** [comment]
:+1:

The sooner we define an API the better – both so we don't become tied to our scheduler and so other providers (Kubernetes, Fleet, etc) can write their own drivers.

**Comment by tnachen** [comment]
@vieux @aluzzardi how do we move forward with this? I think we should start implementing the default one under a interface at the very least.
Also it seems like the current scheduler class is only about the placement of a container, but there is also discovery and managing the state of a cluster.
I think all of this should be pluggable under interfaces.

**Comment by vieux** [comment]
@tnachen you're right, right now, scheduler and discovery are separated. Discovery already has it's own interface (consul, etcd, etc...), but not Scheduler.

You could look at this https://github.com/docker/swarm/pull/178 for an attempt at really basic version of the Scheduler interface.

Regarding mesos I feel like Scheduler and Discovery needs to be blended because swarm won't get a list of nodes, but a list of mesos master.


My dream would be `swarm manage --discovery mesos://<zookeeper_url_with_the_mesos_masters>`

**Comment by vieux** [comment]
Actually, after thinking about this more, I think we don't have to mix Scheduler and Discovery.

This will probably the main use case:
`swarm manage --scheduler mesos --discovery zk://<zookeeper_url_with_the_mesos_masters>/path`

But you should be able to use other discovery mechanism
`swarm manage --scheduler mesos --discovery file://list_mesos_master`

@tnachen what do you think ?

**Comment by tnachen** [comment]
I think I need to understand more if discovery info is going to be used by some other commands or components of swarm.

Seems like discovery is simply listing all the swarm agents, does it also plan to list all the containers or find a particular container in the cluster?

But yes, I think discovery can stay as-is.
I'm thinking that the swarm framework can launch custom executors which launches the swarm agent that will be running on each host, and we can let the custom executor talk to the discovery backend out of band from Mesos if we want to utilize swarm discovery features in the future.

btw @vieux, if a swarm manager dies, how does it bootstrap again to get to know all the running containers?

**Comment by vieux** [comment]
discovery gives you a list of ip/port you need to talk to:
with the default scheduler, it's a list of docker daemon, with mesos I think it'll be a list of mesos master.

right now, when you restart it, it'll reconstruct the cluster cache by reaching all the nodes and asking for their containers.
soon we will have a local cache on disk.
later we will have shared state (probably with raft)

**Comment by tnachen** [comment]
So if you want a list of all the available nodes that you can a docker container, then it's the whole list of slaves (which you can get from querying the JSON endpoint from master).

However just getting the slave nodes doesn't necessarily tell you the swarm endpoints, unless we assume swarm is running on the same port on all the nodes. 

Also it's either an assumption that swarm agent is already preinstalled and running on all your cluster nodes, or the framework actually allows downloading swarm agent and running one per host itself.

I assume the former, where docker daemon is pre-installed.

**Comment by phemmer** [comment]
@tnachen 
Reading your last few comments, they don't make much sense to me. You speak of the swarm agent running on each node, but swarm only runs in one location. It talks to the docker daemon that runs on each node, but doesn't run there itself.

**Comment by phemmer** [comment]
Just some of my thoughts on the whole scheduler thing. I think the scheduler interface will need to be a lot more advanced than just calling out to an external system and asking "what node should I place this container on?".
For example, if we use swarm for our system, we'll need it to be able to do things like handle when a new node comes up or goes down, so that it moves existing containers around to balance things out. Or rebalance containers if one of them starts consuming a lot of CPU.

Thus I think the interface should be more of swarm saying "I have this desired configuration", which would be what containers should be running and their configurations. The scheduler should then tell swarm what to do. If the configuration has a new container being started, the scheduler will tell swarm "start this container on node A". If the scheduler deems that some containers need to be moved around, it might also send "stop container X on node A. start container X on node B"

This scheme also allows the scheduler to move things without being prompted by swarm. Lets say a container starts using a lot of CPU, the scheduler might decide to move this container elsewhere. The move wasn't triggered by any configuration change.

&nbsp;

I also don't think discovery should be tied into the scheduler. In my use case, discovery will be handled by swarm, and swarm will let the scheduler know a node just joined, or is leaving. If both scheduler and discovery happen to actually be the same service, thats fine, but swarm shouldn't know that.

**Comment by tnachen** [comment]
@phemmer I'm looking at the example usage and also the discovery, and it seems to me that in order to be discovered you need to run the agent on each node in your cluster. Is this not true?

**Comment by phemmer** [comment]
@tnachen Actually no. This is everyone's first thought when the see the swarm readme :-)
The `swarm join --discovery token://FOO --addr=BAR` action can actually be run from any node. All this does is publish the address of the docker daemon to the token based discovery service. It's a one-time registration operation. The swarm manager then reaches out to the discovery service to get a list of docker daemons that it needs to connect to.

**Comment by tnachen** [comment]
@phemmer I see, the comments does it make it very confusing:
# on each of your nodes, start the swarm agent

**Comment by tnachen** [comment]
I'm not all familiar with the intentions and the code, but it seems like just looking at join.go alone, it seems to imply that it's meant to run on each node as it continues to callback register in a infinite loop with heartbeat timeout. If it's just a one time registration it seems unnecessary, and definitely doesn't make sense to run a bunch of loops in one node just giving ip addresses.

**Comment by phemmer** [comment]
Actually it looks like I'm somewhat wrong. The agent does stay running. It pings the discovery service periodically to let it know the node is still there. It's been a few months since I played with it, so apparently I'm out of date. I appologize.

**Comment by aluzzardi** [comment]
Implemented \o/

**Comment by ppadala** [comment]
@aluzzardi - can you point me to the documentation on plugin API and how to create them?

**Comment by vieux** [comment]
@ppadala hello, there is no documentation really. You have to implement this interface: https://github.com/docker/swarm/blob/master/cluster/cluster.go

**Comment by vieux** [comment]
@ppadala I'm opening an issue to create documentation.

**Comment by ppadala** [comment]
Thanks, @vieux. How do I install and register the plugin? If there's example code somewhere, please point me to it.

**Comment by vieux** [comment]
@ppadala you have to add a `case` to this `switch` https://github.com/docker/swarm/blob/master/cli/manage.go#L258

**Comment by ppadala** [comment]
@vieux Is it expected that third party Swarm plugins live in docker tree and built together for now? Will there be a plugin architecture similar to volumes and libnetwork in the future?

**Comment by vieux** [comment]
@ppadala yes, we are thinking about a plugin architecture, for now they are to be checked in in the code.

**Comment by ppadala** [comment]
Thanks for the quick responses @vieux.

Slight digression, but is there a way to find the Swarm ID from a container ID? It looks like currently Swarm master gets the container association by querying the Docker engines on each of the hosts. We are experimenting with sharing hosts across Swarm clusters and need a way to distinguish containers by Swarm IDs.

I see that labels are a way to distinguish containers, but they have to be set by the users.

**Comment by eyeofthefrog** [comment]
Is there an issue open for the plugin architecture?
