### ISSUE TITLE
Swarm 1.2.0 potentially making incorrect call to Consul API for creating sessions

### ISSUE THREAD

**Issue by mrapczynski** [docker/swarm#2153]
I attempted to upgrade to Swarm 1.2.0 tonight, but failed because both Swarm manager and Consul are constantly dumping messages like the following:

```
Apr 20 19:09:28 dockermgmt.ad.fhda.edu consul[13105]: 2016/04/20 19:09:28 [ERR] http: Request PUT /v1/session/create, error: rpc error: Invalid Session TTL '7500000000', must be between [10s=24h0m0s] from=172.17.0.4:39249
Apr 20 19:09:38 dockermgmt.ad.fhda.edu consul[13105]: 2016/04/20 19:09:38 [ERR] http: Request PUT /v1/session/create, error: rpc error: Invalid Session TTL '7500000000', must be between [10s=24h0m0s] from=172.17.0.4:39249
Apr 20 19:09:48 dockermgmt.ad.fhda.edu consul[13105]: 2016/04/20 19:09:48 [ERR] http: Request PUT /v1/session/create, error: rpc error: Invalid Session TTL '7500000000', must be between [10s=24h0m0s] from=172.17.0.4:39249
Apr 20 19:09:58 dockermgmt.ad.fhda.edu consul[13105]: 2016/04/20 19:09:58 [ERR] http: Request PUT /v1/session/create, error: rpc error: Invalid Session TTL '7500000000', must be between [10s=24h0m0s] from=172.17.0.4:39249
Apr 20 19:10:08 dockermgmt.ad.fhda.edu consul[13105]: 2016/04/20 19:10:08 [ERR] http: Request PUT /v1/session/create, error: rpc error: Invalid Session TTL '7500000000', must be between [10s=24h0m0s] from=172.17.0.4:39249
Apr 20 19:10:18 dockermgmt.ad.fhda.edu consul[13105]: 2016/04/20 19:10:18 [ERR] http: Request PUT /v1/session/create, error: rpc error: Invalid Session TTL '7500000000', must be between [10s=24h0m0s] from=172.17.0.4:39249
Apr 20 19:10:28 dockermgmt.ad.fhda.edu consul[13105]: 2016/04/20 19:10:28 [ERR] http: Request PUT /v1/session/create, error: rpc error: Invalid Session TTL '7500000000', must be between [10s=24h0m0s] from=172.17.0.4:39249
```

I downgraded back to 1.1.3, and then I could control the cluster again.

**Comment by abronan** [comment]
Hi @mrapczynski, so the default `LockTTL` should be at `20s` now which should work by default for all configs on every store. Are you using the `--replication-ttl` flag at a value of `15s` by any hazard? Otherwise to circumvent that, you can use a `config.json` on Consul startup with:

```
{"session_ttl_min": "5s"}
```

And this will solve the issue.

**Comment by mrapczynski** [comment]
@abronan Yes incidentally it is 15s! How did you know? Does that drive a calculated value elsewhere?

I'll try the Consul config in the meantime - easy change.

**Comment by abronan** [comment]
@mrapczynski Yes :smile: Consul divides the TTL by `2x` and does not support `TTLs < 10s` by default. So an acceptable default value for Consul is `20s` minimum for `--heartbeat` and `--replication-ttl`, otherwise you have to specify the `session_ttl_min` on Consul config (we have to do that in the CI to speed up tests).

I'm glad you made it all work! Closing this one but feel free to open a new issue if you have any more questions :)
