### ISSUE TITLE
swarm can not schedule when contaier config has cpushares

### ISSUE THREAD

**Issue by davidstack** [docker/swarm#2227]
1. i try to create a container in mysql swarm cluster  with this config:
{"Name":"wangdk789","Env":["constraint:node==docker-swarm1.novalocal"],"NetworkDisabled":true,"Labels":null,"HostConfig:{"Memory":104857600,"MemorySwap":104857600,"CpuShares":512}} 
It failed with this result:
no resources available to schedule container
2.but when i create the container in a docker host with the same config,it succeed.
3. when i remove the cpushare configuration,then it succeed in the swarm cluster

**Comment by allencloud** [comment]
@davidstack 
Actually, What you said is totally normal.
Maybe you can take a look at https://github.com/docker/swarm/blob/master/docs/swarm-api.md.
In that, docs said: 
```
POST "/containers/create"	
CpuShares in HostConfig sets the number of CPU cores allocated to the container.
```
The root cause is the difference in implementing endpoint between Swarm and Docker Host.

**Comment by davidstack** [comment]
@allencloud  thank you. 
 you mean CpuShares is different in swarm and docker? am i right ? but ,how can i configure container cpu in swarm 
the code in github.com/docker/swarm/scheduler/strategy/weighted_node.go i found this:
```
if config.CpuShares > 0 {
			cpuScore = (node.UsedCpus + config.CpuShares) * 100 / nodeCpus
		}
```

but. i don' find how the swarm CpuShares convert to the docker CpuShares

**Comment by allencloud** [comment]
@davidstack 
Yes, **CpuShares is different in swarm and docker**.
Because cpushares in cgroups is a relative value to compare with containers on the same operating system, While Swarm schedules containers on lots of machines.

When a user hopes to share cpu times with cpushares 512 both for container A and container B, then if both containers are on the same machine, the cpushares 512 for each one makes sense. If not on the same machine, it will not take affect to set both cpushares 512.

But as long as we use `constraint:node==docker-swarm1.novalocal` to specify one node, cpushares is useful.

**Comment by davidstack** [comment]
@allencloud 
ok,i understand . i think the CpuShare in swarm  should has the same meaning with Vcpu (just as OpenStack).

docker host should report its vcpu info to swarm manager.  so swarm can  calculate the CpuShare used in docker according vcpu info .
just a thought

**Comment by dongluochen** [comment]
@davidstack Point taken. The Docker relative CpuShares doesn't fit Swarm model. We may incorporate other fine grain CPU measure in the future.
