### ISSUE TITLE
Add support for user defined script to generate labels.

### ISSUE THREAD

**Issue by timothysc** [docker/swarm#239]
The idea here is piped|configs.  

--labels=|/usr/bin/generate_json_or_yml_nvp_thunk.sh  

This is nice because different folks could create their own script files to detect: 
- cluster/rack awareness
- gpu capabilities 
- over provisioning mechanics ...

**Comment by vieux** [comment]
Hi @timothysc 

Are you talking about host labels ? In this case the issue should go in docker directly.

**Comment by vieux** [comment]
in any case, I like the idea

**Comment by timothysc** [comment]
@vieux 
Yes I'm talking host labels, but I can't claim the idea as my own, I've stole it from several other schedulers/cluster managers. 

;-)

**Comment by tnachen** [comment]
also ideally this should be dynamic, where it can be updated without restart. But that's a nice to have :)

**Comment by timothysc** [comment]
@tnachen - of course ;-)

**Comment by vieux** [comment]
right now we don't have dynamic host labels, we had a long discussion about it.

You start your daemon with `--label storage=ssd`

Then you schedule a few container with `-e constraint:storage=ssd`

Then you update your host label to `storage=disk`

What happen for your container ? Because it isn't matching the constraint anymore.

**Comment by tnachen** [comment]
@vieux there are certainly a lot of things to handle when it comes to dynamic attributes/labels, so I'm not proposing we need to have it.
But from the experience of Mesos, there are quite some scenarios that is great with dynamic label updates. 
In the situation you described, it certainly depends on the policy of how to handle this. It certainly deserves a seperate ticket but I this is not high pri at all.

**Comment by vieux** [comment]
@tnachen cool, we'd love to hear more about your experience soon.

@timothysc can you open this ticket on the docker repo ?

**Comment by thaJeztah** [comment]
But does *not* having dynamic labels really prevent this situation? Stop/Starting the daemon would still allow changing the labels?

**Comment by vieux** [comment]
@thaJeztah stop/start the daemon kills the container, so there is no question, the container won't restart and will be rescheduled if another machine with the "old" label is available

**Comment by abronan** [comment]
@vieux Actually, the scenario you mentioned is a good case for container migration.

If a container does not match a constraint anymore due to dynamically changing labels, then Swarm (or the underlying pluggable scheduler) should know about that and trigger a migration after a new scheduling decision (live or not, it depends on the feasibility). It really depends on if we accept to stop/kill the container before re-scheduling it onto another machine.

I guess that if we consider the use of dynamic labels in the future, we must first deal with the question of host-to-host migrations and how this might work with pluggable schedulers.

Sorry, I digress. I like the idea of the PR :)

**Comment by timothysc** [comment]
@thaJeztah @vieux label persistence can be independent of the daemon itself. 

In fact it should be to enable recovery of stateful data.  

In order to truly do stateful services you would need some other moving pieces, but I'll leave that for another ticket.

**Comment by timothysc** [comment]
Closing re: @vieux comments.
