### ISSUE TITLE
make --auto-accept handling more manageable

### ISSUE THREAD

**Issue by dayglojesus** [docker/swarm#2416]
Hi,

The current implementation of the CLI `--auto-accept` for `docker swarm` is awkward.

Currently, if we want to specify auto-accept for both managers and workers, we need to add the arg to the CLI twice: `docker swarm --auto-accept manager --auto-accept worker`

This is straightforward, but the interface does not map to policy storage, nor lend itself to "toggling" -- for example, if one needed to disable auto-accept for managers.

A more direct approach might be to allow: `docker swarm --auto-accept-<role> true/false`

**Comment by dongluochen** [comment]
@dayglojesus Your issue is for Docker 1.12 swarm mode. Please open issue at https://github.com/docker/docker/issues and close this one.  

Some clarification between the projects is available at https://github.com/docker/swarm
Section "Swarm Disambiguation". Thanks for your contribution to Docker projects.

**Comment by dayglojesus** [comment]
Sorry
