### ISSUE TITLE
Version 1.2.4 not tagged in github

### ISSUE THREAD

**Issue by bcornec** [docker/swarm#2428]
While version 1.2.4 is announced and tagged in https://github.com/docker/swarm/blob/master/CHANGELOG.md from 2016-07-20, it is not yet available as a tag in github (only rc are available). Or is the changelog incorrect by documenting the rc without saying so ?

I'm looking at packaging the latest version for Mageia 6 which is due soon.

**Comment by nishanttotla** [comment]
@bcornec good question, sorry for the confusion! Historically, we've had an updating changelog for the upcoming release, which is why it's this way right now.

I agree this can be confusing, and we'll change that. To clear any confusion, `1.2.4` is due for final release on Thursday (July 28), and is in the `rc2` stage right now.

**Comment by dongluochen** [comment]
How about we put RC tag in CHANGELOG.md? It'd be replaced by official release.

**Comment by bcornec** [comment]
Yes, that would solve the issue/confusion.

**Comment by nishanttotla** [comment]
@bcornec we're releasing 1.2.4 today. From now on, we'll mention RCs in the CHANGELOG.
