### ISSUE TITLE
Failed to follow the doc `Evaluate Swarm in a sandbox` to create a swarm 

### ISSUE THREAD

**Issue by dongluochen** [docker/swarm#2441]
Issue was opened at https://github.com/docker/docker/issues/24982. But it should be resolve at Swarm. 

cc @twang2218 @sblackstone.

**Comment by twang2218** [comment]
I'm not quite sure #2442 is a fix for the problem. By using `docker-machine --swarm`, the details of how to build the swarm are hidden. 

My purpose of the demo is to show people, how to build the swarm manually by `docker run swarm`. By following the "Evaluate Swarm in a Sandbox" doc, I could show the steps to people, however, not anymore.

So, by using `--swarm` to hide the details is not actually helped for my issue.

**Comment by yaron-idan** [comment]
I've also failed to use this guide in order to start a Swarm sandbox. All images were run as expected but the nodes don't discover each other and docker info tells me my cluster has no nodes.
I did manage to create a cluster very quickly with the script provided in this SO question - http://stackoverflow.com/questions/38666566/troubles-using-docker-machine-to-setup-swarm, so I'm thinking the problem might be in the token I'm providing for discovery.
What do you think?

**Comment by twang2218** [comment]
I still don't think #2442 is a fix to the original problem, it's a workaround. But the original problem is still there. We need to figure out a way to why the TLS broken, and fix the instruction, rather than just cover the details with `--swarm` option.

**Comment by dongluochen** [comment]
@twang2218 There are 2 docs on how to set up TLS on Docker and Swarm. Docker machine is a provisioning tool to create Linux servers with Docker installed. You can start from there to configure TLS. 

https://docs.docker.com/engine/security/https/
https://github.com/docker/swarm/blob/master/docs/configure-tls.md
