### ISSUE TITLE
Has work on swarm ceased?

### ISSUE THREAD

**Issue by vincentwoo** [docker/swarm#2507]
https://github.com/docker/swarm/graphs/commit-activity shows a big dropoff compared to swarmkit or docker engine. The README says that swarm is "not deprecated", but is anyone at Docker still working on this project full-time?

**Comment by originalgremlin** [comment]
Also curious about this.  I love the basic abstraction of allowing a cluster of nodes to appear as a single docker engine but am worried that this project has been abandoned in favor of swarmkit.

**Comment by dongluochen** [comment]
Swarmkit is more natural in supporting service model and it's getting a lot of usage since launch. Much resource has put into Swarmkit as orchestration platform.

At the same time Swarm is actively used by many users in their infrastructure. Our current goal is to keep Swarm stable. Inside Docker we favor bug fixes over feature requests on Swarm. But users are welcome to contribute anything they consider appropriate.

**Comment by vincentwoo** [comment]
I'm going to assume that Docker is basically putting original swarm on life support. I opened a pretty important, straightforward bug about lack of documentation on a totally basic thing almost exactly a year ago and it hasn't been addressed: https://github.com/docker/swarm/issues/1341.

I think you should be more honest in the README about your true plans for the project. "Docker does not currently have a plan to deprecate Docker Swarm" communicates very little about your true intentions.
