### ISSUE TITLE
what happend to docker swarm when i restart all nodes in swarm at the same time?

### ISSUE THREAD

**Issue by KielChan** [docker/swarm#2511]
CST 16:31.
I have encountered with a problem when I do something with docker swarm cluster.'cos I need multi image sources to get tarball to start my containers,when I start the no.1 docker service(with the order docker service create),I changed the docker image sources by modift /etc/default/docker and then restart the docker service at the same time(to my swarm cluster, all 3 nodes are all manager).when I run the order 'docker node ls',yes ,it's ok, but when I do something with the serices which started before, it does not work gracelly(the output may like this, Error response from daemon: rpc error: code = 4 desc = context deadline exceeded **or** Error response from daemon: rpc error: code = 2 desc = raft: no elected cluster leader  ).
how could i fix the 'bugs',and the phenomenon caused by restart docker service at the same time(by ansible scripts)

**Comment by nishanttotla** [comment]
@KielChan your issue is related to Docker Swarm Mode, which is different from the github.com/docker/swarm project. See "Swarm Disambiguation" for details: https://github.com/docker/swarm/blob/master/README.md

I'm closing this issue, but can you please open this issue on the github.com/docker/docker repo?
