### ISSUE TITLE
Manager and Worker on the same host (node)

### ISSUE THREAD

**Issue by lzalewsk** [docker/swarm#2532]
Hi,
Question.
Is it possible to run Manager and Worker on the same host?
If yes. How to do it? Any hints?

**Comment by allencloud** [comment]
Hi @lzalewsk 
I am afraid your issue is related to Swarm Mode in Docker Engine. You had better put forward an issue in project docker/docker (https://github.com/docker/docker/issues). 

Further, you can read https://github.com/docker/swarm#swarm-disambiguation for more details.

Closing this. If you need help, please reopen and just ask us.
