### ISSUE TITLE
Problem create service with parameters

### ISSUE THREAD

**Issue by ildarmf** [docker/swarm#2544]
Hello!

I have docker image, I want to run this image in swarm with replicas with the following parameters(volumes, ports, env, command) 

How can I do that?

Example:
This command works:
`docker service create --with-registry-auth --name low --replicas=5 image`

What i want
`docker service create --with-registry-auth --name low --replicas=5 image --env= {user=test, sign='qwerty' }  --volume=/data command=sh bin/start.sh`

**Comment by allencloud** [comment]
Hi @ildarmf Thanks for your feedback.

I am afraid that your issue is related to Swarm Mode of docker engine, maybe it is more proper to post issue here https://github.com/docker/docker/issues/new . This project is about Swarm which is different from swarm mode in docker engine.

Here are more details about the difference https://github.com/docker/swarm#swarm-disambiguation

I am closing this. If you need more help, feel free to let us know. Thanks again for your contribution.
