### ISSUE TITLE
Rouge duplicate node cannot be deleted

### ISSUE THREAD

**Issue by ThePixelBro22** [docker/swarm#2588]
I have a swarm of 20 nodes, and for some reason one of the nodes cloned itself and I cannot remove it.

```
ID                           HOSTNAME             STATUS  AVAILABILITY  MANAGER STATUS
05vk86j6pzwj4ovbuwxybclbd    swarm-dc1-pi02       Ready   Active        Reachable
0t1j3dg14dh3fkht19zs3rzgx    swarm-dc1-pi18       Ready   Active
12h0s2ilvvztb9mecj2eo2g0s    swarm-dc1-pi12       Ready   Active
36sfnurxxn5mys7mdrrhgby8s    swarm-dc1-pi05       Ready   Active
3o9k13fmkmuol2o86m7bxfq6r *  swarm-dc1-host       Ready   Active        Leader
42c3kwt9wrnuu8ydt3mq6ezow    swarm-dc1-pi13       Ready   Active
4g8cs0npagkwdcy5m92q7x6fb    swarm-dc1-pi07-main  Ready   Active
53lowaeyx0ylq54xojdhk4gx6    swarm-dc1-pi07       Down    Active
5x6d4vrsw983cgy9m7h87xd4p    swarm-dc1-pi01       Ready   Active
72v1qb5nwnk41sz5cucilxb0i    swarm-dc1-pi04       Ready   Active
73wrqac5rml6f6h7vfsbxtww9    swarm-dc1-pi08       Ready   Active
```
So there was 2 node #07 but i renamed the acual one so i can try and remove the glitched one.

So when I run
`docker node rm --force swarm-dc1-07
`
I get
`Error response from daemon: node swarm-dc1-07 not found
`

**Comment by dongluochen** [comment]
@ThePixelBro22 Your issue is associated with swarmkit, not classic Swarm (this repo). For your specific issue, have you try `docker node rm 53lowaeyx0ylq54xojdhk4gx6`.  If it doesn't work, you may open issue at https://github.com/docker/docker/issues/. And provide reproduce steps. 

The difference between the 2 project is stated at https://github.com/docker/swarm#swarm-disambiguation.
