### ISSUE TITLE
Swarm 1.2.6 reports bad revision

### ISSUE THREAD

**Issue by vincentwoo** [docker/swarm#2597]
probably bundling script issue:

```
vwoo@ubuntu:~$ swarm --version
swarm version 1.2.6 (`git rev-parse --short HEAD`)
```

Binary was downloaded straight from github and placed in `/usr/local/bin`.

**Comment by allencloud** [comment]
I could reproduce that. Maybe something wrong in the Dockerfile. Working on it now.

**Comment by allencloud** [comment]
It comes when we bump from 1.2.5 to 1.2.6, since here we use a base image from golang:1.5.4-alpine to golang:1.7.1-alpine.

Then in command:
```
OARCH=$GOARCH GOOS=$GOOS CGO_ENABLED=0 go install -v -a -tags netgo -installsuffix netgo -ldflags '-w -X "github.com/docker/swarm/version.GITCOMMIT=`git rev-parse --short HEAD`" -X "github.com/docker/swarm/version.BUILDTIME=`date -u`"'
```
We cannot execute `git rev-parse --short HEAD` and `date -u` first. I think since version 1.6.0, golang introduced this issue.

ping @dongluochen @nishanttotla

**Comment by nishanttotla** [comment]
Thanks for reporting @vincentwoo, we'll need to fix this.

Also cc @vieux
