### ISSUE TITLE
Troubles with overlay networks - cannot ping service

### ISSUE THREAD

**Issue by Riziero** [docker/swarm#2604]
Hello,

I am creating a swarm cluster and then an overlay network which I am then using to spin up services. It appears that by trying to constraint a service to run on a specific node (--constraint node.hostname==node3) then the overlay network does not work.

As in I can not ping a service by its name from other services in the same network.
As soon as I get rid of the node contraint everything goes back to being pingable again.

Anyone have any clue about this?

Thanks!

**Comment by allencloud** [comment]
Hi @Riziero Thanks for your feedback.

I am afraid that your issue is related to Swarm Mode of docker engine, maybe it is more proper to post issue here https://github.com/docker/docker/issues/new . This project is about Swarm which is different from swarm mode in docker engine.

Here are more details about the difference https://github.com/docker/swarm#swarm-disambiguation

I am closing this. If you need more help, feel free to let us know. Thanks again for your work.

**Comment by Riziero** [comment]
Many thanks for the lead :)
