### ISSUE TITLE
Docker multihost networking with overlay driver --opt encrypted : cannot join secure network: encryption keys not present

### ISSUE THREAD

**Issue by bklau** [docker/swarm#2606]
Steps to repo:

1. Install Docker 1.12.2
2.  Configure Swarm multihost networking using EXTERNAL KV store like Consul(NOT Swarm mode)
3. docker network create -d overlay --opt encrypted my_overlay
4. docker create nginx
5. docker network connect my_overlay <container_id created above>
6. docker start  <container_id created above> and you will get an error:

"Error response from daemon: cannot join secure network: encryption keys not present"

Note: If you leave out the "--opt encrypted" when created the overlay network, it works fine.

**Comment by dongluochen** [comment]
`--opt encrypted` is a Docker Swarm-mode only feature. It's not supported in classic Swarm. The problem is classic Swarm doesn't have encryption key management. Docker Swarm-mode has built-in key management, which includes built-in CA, key distribution channel, and key rotation procedure. This is outside the scope of classic Swarm so it's not able to support `--opt encrypted`.
