### ISSUE TITLE
Expose a range of ports in docker service

### ISSUE THREAD

**Issue by rsabir** [docker/swarm#2616]
Is there any way to expose a range of ports in the creation of a swarm service ( for instance: `-p 1024-2000:1024-2000`)? I know that it's possible for a container, but is it also possible for a Swarm Service? If yes, I can't find how to do that in the documentation.

I need this functionality for exposing a service that contains vsftpd.

**Comment by allencloud** [comment]
Do you mean the service created via docker cli command `docker service create`? @rsabir

**Comment by rsabir** [comment]
@allencloud yes

**Comment by allencloud** [comment]
Hi @rsabir, thanks for your feedback.

I am afraid that your issue is related to Swarm Mode of docker engine, maybe it is more proper to post issue here https://github.com/docker/docker/issues/new . This project is about Swarm which is different from swarm mode in docker engine.

Here are more details about the difference https://github.com/docker/swarm#swarm-disambiguation

I am closing this. If you need more help, feel free to let us know. Thanks again for your contribution.

**Comment by rsabir** [comment]
Thank you @allencloud , I have opened the same issue in docker/docker registry: https://github.com/docker/docker/issues/30560
