### ISSUE TITLE
"Docker does not currently have a plan to deprecate Docker Swarm. "

### ISSUE THREAD

**Issue by ORESoftware** [docker/swarm#2623]
Why is this in the readme:

"Docker does not currently have a plan to deprecate Docker Swarm."

Was Docker planning to deprecate Swarm?

**Comment by riuvshin** [comment]
I think that message appeared due to tons of questions which rised after docker announced "docker swarm mode" which means that swarm is embedded in docker, with this community had a feeling that swarm standalone can be deprecated and those who uses swarm standalone like me ^_^ were really scared because "swarm mode" absolutely does not equivalent with swarm. So I can't say for sure but I really hope that swarm will be there as a separate product unless swarm mode will be able to cover all swarm usecases.

**Comment by dongluochen** [comment]
@riuvshin Thanks for the reply. That's the intention.

**Comment by nishanttotla** [comment]
Closing the issue since the question was answered.

@ORESoftware please feel free to re-open if you had more questions.

**Comment by thiagofigueiro** [comment]
The Docker Swarm standalone documentation gives a different impression by stating that "most users should use integrated swarm mode":

![Docker Swarm standalone](http://i.imgur.com/FC6iBhx.png)

This is one of the worst feature naming decisions I have ever seen.

It would be great to have https://docs.docker.com/swarm/overview/ updated to re-iterate that swarm standalone is not going anywhere.

**Comment by nishanttotla** [comment]
@thiagofigueiro Swarm mode is simply something that more users want, and whose use cases are better served by the service and state reconciliation abstractions, something that Swarm standalone does not provide.

That said, we do have active users who still continue to use standalone Swarm, and we are actively working on and maintaining it.

cc @mstanleyjones for opinion on docs.

**Comment by mstanleyjones** [comment]
I think the situation is accurate. Most users should be using swarm mode unless their use case is better addressed by standalone swarm or they are maintaining legacy set-ups. I don't think docs changes are needed at this time, unless I'm missing something.

**Comment by thiagofigueiro** [comment]
Thanks for the quick responses - you guys are awesome. 

The reason I came to this thread is because, upon reading the docs, I was uncertain of standalone'a future. 

Perhaps it's just me but, if you get more people asking the same question, you might reconsider updating the documentation to make it clearer that standalone is still supported.

**Comment by mstanleyjones** [comment]
To be  clear, if it wasn't supported we would remove it from the docs.
