### ISSUE TITLE
Replica/Service Info from Swarm Service Container

### ISSUE THREAD

**Issue by dondre** [docker/swarm#2629]
I'd like to write code in my container specific to whether or not it's the leader (ie. first instance) of it's parent service. Only thing I've been able to find remotely helpful is IFCONFIG ipaddr showing an IP increment, but the count is different on each host. Is this possible?

**Comment by allencloud** [comment]
Hi @dondre , thanks for your feedback.

I am afraid that your issue is related to Swarm Mode of docker engine, maybe it is more proper to post issue here https://github.com/docker/docker/issues/new . This project is about Swarm which is different from swarm mode in docker engine.

Here are more details about the difference https://github.com/docker/swarm#swarm-disambiguation

I am closing this. If you need more help, feel free to let us know. Thanks again for your contribution.
