### ISSUE TITLE
swarm node cann't start

### ISSUE THREAD

**Issue by timchenxiaoyu** [docker/swarm#2637]
level=info msg="API listen on /var/run/docker.sock"
 Started Docker Application Container Engine.
level=error msg="agent: session failed" error="rpc error: code = 14 desc = grpc: the connection is unavailable" module="node/agent"

Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by dongluochen** [comment]
I think your question is related to Swarm Mode not this project (classic Swarm) because classic Swarm doesn't use grpc. You can find the difference of the 2 projects [here](https://github.com/docker/swarm#swarm-disambiguation). Swarm mode docs are [here](https://docs.docker.com/engine/swarm/). You may open issue at  https://github.com/docker/docker for Swarm mode problems.
