### ISSUE TITLE
Implement 'wait for' flag in docker node drain command

### ISSUE THREAD

**Issue by avielb** [docker/swarm#2699]
Hey,
There should be a flag for:
`docker node update --availability drain <node-id>` command which allows to wait until swarm services are completely rebalanced in the cluster. 

This could be very useful for automating docker engine updates with the newer versioning and releasing mechanism in community edition.

**Comment by avielb** [comment]
Up!

**Comment by allencloud** [comment]
Hi, @avielb . Thanks for your feedback.

I am afraid that your issue is related to Swarm Mode of docker engine, maybe it is more proper to post issue here https://github.com/docker/docker/issues/new . This project is about Swarm which is different from swarm mode in docker engine.

Here are more details about the difference https://github.com/docker/swarm#swarm-disambiguation

I am closing this. If you need more help, feel free to let us know. Thanks again for your contribution.
