### ISSUE TITLE
Info hangs while events are being flushed to slow readers

### ISSUE THREAD

**Issue by alexmavr** [docker/swarm#2718]
In the events handler, swarm managers are currently holding a write lock while flushing events to listeners (https://github.com/docker/swarm/blob/master/api/events.go#L120-L142). If this flush operation takes more time than expected, such as due to a slow or inactive reader, then this causes all `/info` requests on the leader swarm manager to hang for that duration, as the handler for info attempts to calculate the number of listeners, which requires a read lock on the events handler (https://github.com/docker/swarm/blob/master/api/events.go#L149).

Steps to reproduce:
1) Provision 1 classic swarm manager and 1 docker node
2) Create several event listeners from different nodes using `docker events`, and background these processes on the shell using `Ctrl+Z`. This will maintain the TCP connection active, but no events will be actively read by these listeners.
3) Populate events on the cluster by continuously running `docker -H manager:port run --rm hello-world` with 0.1 second gap.
4) Perform a `docker -H manager:port info` and expect it to hang

Potential courses of action for a resolution:
1) Remove the number of event listeners from the response of Info. The CLI doesn't pretty-print that field, so the use case is fairly limited. Technically this is a functionality regression so it should be the least preferred resolution
2) Remove the read lock on the `Size` method of the event handler. Instead, we can maintain an integer counter that is incremented and decremented appropriately together with entries to `eh.ws`. We can use a separate lock to ensure atomicity of the `delete/decrement`, `add/increment` operations, and have the `Size` operation hold that lock instead, which will have a much smaller critical section.
3) Flush the `http.ResponseWriter` outside of the critical section of the `eventsHandler.Handle` method. This may result in events appearing after delays, or in large chunks, so I'm not sure if that's the easiest approach

**Comment by aaronlehmann** [comment]
I think the right way to fix this is to maintain separate event queues for each listener (perhaps with go-events), or separate positions in a shared queue. Then each listener should have its own goroutine that reads from the queue and pushes events to the socket. Trying to flush an event to every listener before moving on to the next event is a big problem.

I don't think (1) or (2) are acceptable solutions because they would allow slow readers to block delivery of events to other event readers. (3) probably suffers from this as well unless `Handle` is reworked to write to the various sockets in separate goroutines.

cc @dongluochen @wsong

**Comment by dongluochen** [comment]
> Flush the http.ResponseWriter outside of the critical section of the eventsHandler.Handle method. This may result in events appearing after delays, or in large chunks, so I'm not sure if that's the easiest approach

This doesn't work because concurrent `Flush` to the same writer would result in panic. See https://github.com/docker/swarm/issues/2624.

**Comment by dongluochen** [comment]
I agree with @aaronlehmann's solution. (1) and (2) may relieve the immediate `/info` issue. But as long as `/events` is blocked, Swarm would fail. 

We should separate event generation from event consumption. The generator dispatches events into a channel for each listener. The events are flush to the listeners separately. If a listener doesn't consume data (detected by write deadline), break this listener. 

If we don't want to implement separate channels right away, we can add a zombie listener detection with write deadline and break zombie connections. This would allow Swarm manager to recover from hanging listeners.

**Comment by dhiltgen** [comment]
Related to https://github.com/docker/docker-e2e/issues/215

**Comment by aluzzardi** [comment]
There's a 4th solution here which is to rewrite the event handler using https://github.com/docker/go-events

It's a larger functionality change, but in terms of code change we'd actually end up simplifying this a lot since go-events is doing exactly what this code is doing, except it's battle tested (swarmkit and distribution make heavy use of it).

**Comment by aaronlehmann** [comment]
I agree with using go-events here. I suggested this to @dongluochen and @alexmavr previously, but don't seem to have mentioned it in this ticket.

**Comment by aaronlehmann** [comment]
Is anyone working on this issue? Let me know if I can be any help.

**Comment by nishanttotla** [comment]
@aaronlehmann I'm starting to work on this issue today, I will keep you in the loop. I've marked it as P0 for the upcoming release.
