### ISSUE TITLE
Deploy service on specific multiple nodes

### ISSUE THREAD

**Issue by Pierpaolo1992** [docker/swarm#2719]
I have created 3 VM using docker-machine. These VM , named MANAGER, WORKER1 and WORKER2, runs docker engine version;

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 21:43:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 21:43:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
I want to deploy a service on only, for example, MANAGER and WORKER1 nodes.
I've initialized swarm (VM MANAGER is the swarm leader) and then  the two others VM (WORKER1 and WORKER2) joins to the swarm. 

Then i pull in each VM a docker image, named for example MYIMAGE; then inside MANAGER VM i run:

`
docker service create --name cdn-dash  -e contraint.node==NEWMANAGER --replicas 2 -e constraint.node==WORKER1 --publish mode=host,target=80,published=9500,protocol=tcp MYIMAGE`

I expect that two service tasks are deployed on MANAGER and WORKER1 VMs.. but the result is then there is a service task on WORKER1 and another one on WORKER2.. why?

**Comment by allencloud** [comment]
Hi, @Pierpaolo1992 . Thanks for your feedback.

I am afraid that your issue is related to Swarm Mode of docker engine, maybe it is more proper to post issue here https://github.com/docker/docker/issues/new . This project is about Swarm which is different from swarm mode in docker engine.

Here are more details about the difference https://github.com/docker/swarm#swarm-disambiguation

I am closing this. If you need more help, feel free to let us know. Thanks again for your contribution.
