### ISSUE TITLE
Deploy a service in host mode with multiple port mapping

### ISSUE THREAD

**Issue by Pierpaolo1992** [docker/swarm#2720]
I have docker version:

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 21:43:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 21:43:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

And i want to deploy a service in `host mode`: in this way i can map service ports on host. I want to create a service in host mode with multiple port mapping.. 

I could only do something like:

`docker service create --name service_balancer  --publish mode=host,target=80,published=80,protocol=tcp --publish mode=host,target=81,published=81,protocol=tcp MYIMAGE `

or is there something easier for multiple port mapping in host mode?

**Comment by allencloud** [comment]
Hi, @Pierpaolo1992 . Thanks for your feedback.

I am afraid that your issue is related to Swarm Mode of docker engine, maybe it is more proper to post issue here https://github.com/docker/docker/issues/new . This project is about Swarm which is different from swarm mode in docker engine.

Here are more details about the difference https://github.com/docker/swarm#swarm-disambiguation

I am closing this. If you need more help, feel free to let us know. Thanks again for your contribution.
