### ISSUE TITLE
Swarm config

### ISSUE THREAD

**Issue by ssoto** [docker/swarm#275]
I''m trying swarm and I have some doubts related with the configuration. It looks so simple but I cant do it work. I have two servers, both with docker `1.4.1` and `go1.3.3`. I configure docker service to listen by a port 

I can run the client with -H option to send commands between servers. Now come swarm part. I create de unique id from one of their and I try to join to first one from the other, but the command is frozen. Daemons doesn't listen anything 

Any debug test to debug it?

**Comment by vieux** [comment]
We plan to add some debug, the command `swarm join` isn't frozen.
It never returns because it's pinging the discovery service every X seconds.
`swarm join` isn't the server, `swarm manage` is.

Once you have started the `swarm join` on both of your server, you can then start `swarm manage` on any machine, using the same token. Then you configure your docker client to talk to the `swarm manage` IP and port.

Hope this helps
