### ISSUE TITLE
join address can be remote?

### ISSUE THREAD

**Issue by SvenDowideit** [docker/swarm#280]
I just ran `docker-swarm --debug  join --addr=10.10.10.4:2375 ...` on a box other than `10.10.10.4`, and it works. 

is this intentional (atm, it feels useful to me)

**Comment by SvenDowideit** [comment]
also, do _all_ the other nodes need to be able to access the node_ip, or just the manager node (s)?

**Comment by david-guenault** [comment]
This is possible but make no sense. if you use a clustered discovery backend (for example etcd) joining a remote host make no sense because if the remote host crash it will still be available in the discovery backend. And this is really bad for swarm manage scheduling (it will believe that the host is alive and so try to schedule containers on it .... and BOOOM)

**Comment by cpuguy83** [comment]
This makes total sense to me since there is no need of an agent to be running on the daemon host. It's registering a node with swarm.  If swarm can't reach it it will flag it (or it at least shows comm errors in the logs) as not accessible.

**Comment by phemmer** [comment]
Yeah, this is probably a bug in the documentation

>  on each of your nodes, start the swarm agent
>   <node_ip> doesn't have to be public (eg. 192.168.0.X),
>   as long as the other nodes can reach it, it is fine.

Only the manager needs to be able to reach it.

**Comment by david-guenault** [comment]
@cpuguy83 why no need ? docker is agnostic of cluster behaviours. So the host membership need to be managed somewhere else. What i noticied using swarm join (and an etcd cluster discovery backend) is that it update every 25 seconds its entry in etcd. Why updating ? because there is a ttl and if we want to maintain the membership we must do it this way. When a docker host hang the ttl make desapear the entry in the discovery backend so there is no more cluster membership from the failed host. And that's the way it must work. 

You are talking about "swarm can't reach ..." which rôle ? manage or join (aka cluster agent) ? If manager it does not do any cluster management task. 

In the other hand may be it's a swarm bug or bad implementation, but what i say is that it curently work this way. 
```
swarmagent =update=> discoverybackend <=read= swarmmanage
```

**Comment by abronan** [comment]
@phemmer Good catch :+1: at the moment the documentation is unclear.

But what about the case where we'll need to create a Virtual Network between two containers on different hosts (to create links)?

Seems to me that for now (because we don't support links) only the manager needs to be able to reach agents but in the future, agents will need to be able to reach each other as well.

Looks like a dilemma to change the documentation now :sweat_smile:

**Comment by aluzzardi** [comment]
So, the problem is quite simple: We don't support "un-joining" yet :)

`join` and `healthcheck` do two different jobs:
1/ `join` stays alive in order to mark the membership of the node.
2/ `healthcheck` is used to detect **temporary** node failures.

Right now the two features overlap a bit. We are going to rework that soon enough in order to have a more robust health checking and discovery system.

@SvenDowideit, as for `--addr`, it's supposed to be the local node. The reason the flag exists is that your node might have multiple interfaces and you need to specify which address the master can use in order to reach the node.
