### ISSUE TITLE
Swarm Manager errors seen

### ISSUE THREAD

**Issue by bryantidd** [docker/swarm#380]
I'm seeing errors like the following when I join 3 nodes to a consul backend, start a manage process on that cluster (separate machine), remove those nodes from consul (via my own script because there is no leave or housekeeping), join 3 new nodes with the same path in consul backend, stop the manage process , start the manage process again.
ERRO[1061] ID duplicated. BLRC:LDFG:NT7R:ATNF:DHI7:TNPB:F5IT:BJQJ:C4HS:ICMN:7NDX:EQNN shared by XXX.XXX.XXX.XXX and YYY.YYY.YYY.YYY
ERRO[1061] node was already added to the cluster

The errors happens over and over again, I get correct nodes from swarm list, and docker commands seem to run correctly. Just concerned over all the junk in my logs. Is this a real issue or just spurious errors? When will we see housekeeping become a priority?

Thanks for all the good stuff, just want more I guess.

**Comment by vieux** [comment]
The `docker ID` is generated by docker the 1st you launch the daemon.

Here 2 machines have the same ID. It is likely because you installed docker on a VM -> the install start the daemon -> generated an `ID` and then you make copies of the VM.

So all of your machines have the same ID.

You need to remvove `~/.docker/key.json` or `/root/.docker/key.json` and restart the daemon.

Please tell us if you have any other issue.

**Comment by bryantidd** [comment]
Thank you! That's what I needed.

**Comment by maxfields2000** [comment]
These solutions did not work for me on Centos7. There is no ~/.docker file and no key file. While all of my docker daemons do in fact run on VM's, docker was installed by hand on each VM /after/ the VM was imaged.

Where is the ".docker" folder on Centos7?

**Comment by liangsuno** [comment]
It's at /etc/docker/key.json
