### ISSUE TITLE
[Question] swarm cluster

### ISSUE THREAD

**Issue by JasonSoft** [docker/swarm#408]
Hi All,

Sorry for disturbing, I was confused about swarm cluster.  Would you mind helping me, please?

Scenario:
I have three nodes.  Docker is installed on every node.  NodeB and NodeC are joined to swarm manager (NodeA).  For example,

NodeA: 192.168.0.1 (Swarm manager will be run on the node)
NodeB: 192.168.0.2 ( app1 container will be run on the node) 
NodeC: 192.168.0.3

Questions:

1. if NodeB is down, app1 container will be moved to NodeC or NodeA by Swarm.  Is that correct?
2. What happens if NodeA (swarm manager) is down?  Does it mean cluster will fail in this case because master is down?

Thank you for helping.

Thanks,
Jason

**Comment by abronan** [comment]
Hi @JasonSoft,

1. AFAIK, node rebalancing is not yet implemented. You can check the [Roadmap](https://github.com/docker/swarm/blob/master/ROADMAP.md) for more informations. But ideally, yes we'll see **app1** being re-scheduled on **NodeC** (or **NodeA** if there is a Swarm Agent running next to the Swarm Manager) because it has the resources available to host the container. Still, if NodeC has no more resources available to host new containers, the rebalancing should fail because Swarm does not allow *overflowing* by default to avoid *Out of Memory* errors.

2. No, Node instances will still be up and running containers but there are no more entry points to schedule new containers on this cluster. There are two solutions: you can diagnose the reason why the Node running the Swarm Manager is down and wait until it recovers or you can create a new Manager by giving your discovery token or using an external discovery service.

**Comment by JasonSoft** [comment]
Hi @abronan,

Thanks for clarifying.  I was wondering if we could run two Swarm Manager instances ( either master and master mode or master and slave mode) at the same time.  Therefore, if one of manager instances is down, others can take over it.  Is it possible?

Thank you.
