### ISSUE TITLE
Can't build on Mac OS X

### ISSUE THREAD

**Issue by chanezon** [docker/swarm#419]
Following build instructions at https://github.com/docker/swarm#2---alternative-download-and-install-from-source

```
go get -u github.com/docker/swarm
# github.com/docker/swarm/cluster
src/github.com/docker/swarm/cluster/node.go:368: not enough arguments in call to n.client.RemoveContainer
```

pat-2:gocode pat$ go version
go version go1.4.2 darwin/amd64
pat-2:gocode pat$ uname -a
Darwin pat-2.local 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64
pat-2:gocode pat$ git version
git version 1.9.3 (Apple Git-50)
pat-2:gocode pat$ docker --version
Docker version 1.5.0, build a8a31ef

**Comment by vieux** [comment]
@chanezon your dockerclient seems outdated `go get -u` ?

**Comment by chanezon** [comment]
Not sure I understand.
Do I need to build docker from tip in order for swarm build to work?
I'm using docker client latest release https://github.com/boot2docker/osx-installer/releases/tag/v1.5.0

**Comment by vieux** [comment]
@chanezon docker client si hosted here: https://github.com/samalba/dockerclient either you update your docker client ro you install godep and go a `godep go build` to build using the vendored dependencies

**Comment by chanezon** [comment]
Thanks, that worked:-)

**Comment by akaspin** [comment]
> 2 - Alternative: Download and install from source.
Alternatively, you can download and install from source instead of using the Docker image.
Ensure you have golang and git client installed (e.g. apt-get install golang git on Ubuntu). You may need to set $GOPATH, e.g mkdir ~/gocode; export GOPATH=~/gocode.
The install swarm binary to your $GOPATH directory.
go get -u github.com/docker/swarm

:-)

**Comment by osallou** [comment]
Getting same issue. I build it some time ago and it was fine. I upgraded docker (from docker repo) and now swarm fails with:

    ERRO[0000] Node 127.0.0.1:2376 is running an unsupported version of Docker Engine. Please upgrade.

I tried to rebuild swarm but I get same error message

    ldaptop:~/Development/NOSAVE/gocode$ go get -u github.com/docker/swarm
    # github.com/docker/swarm/cluster
    src/github.com/docker/swarm/cluster/node.go:368: not enough arguments in call to n.client.RemoveContainer


ldaptop:~/Development/NOSAVE/gocode$ go version
go version go1.2.1 linux/amd64

**Comment by sonchang** [comment]
@osallou I ran into this yesterday as well.  The problem is swarm currently isn't compatible with the latest version of https://github.com/samalba/dockerclient (which takes in 3 arguments for RemoveContainer).  If you look at https://github.com/docker/swarm/blob/master/Godeps/Godeps.json , you'll see it uses an older version of dockerclient.

**Comment by chanezon** [comment]
Workaround, on Mac OS X, for now as suggested by @vieux 
```
go get -u github.com/docker/swarm
fails
go get github.com/tools/godep
add ~/$GOPATH/bin to PATH
cd src/github.com/docker/swarm
godep go build
```

**Comment by vieux** [comment]
I'm going to update swarm's godep to use the last version of dockerclient.
