### ISSUE TITLE
"discovery" implies that Swarm supports service discovery

### ISSUE THREAD

**Issue by bfirsh** [docker/swarm#472]
Just as a heads up, I have had several people get confused about what "discovery" is in Swarm. They mistakenly assume it is a way for containers to do service discovery (e.g. how does my web server find my database).

I guess it's service discovery for Swarm nodes, but I wonder if there's a better word that could be used so people don't mistake it with a service discovery system they can use for their apps.

For reference, terms used by existing pieces of software:

- Mesos seem to use slave "registration" around their docs.
- Riak uses the word "membership" in that context.
- etcd also use "discovery"

**Comment by thaJeztah** [comment]
Valid concern (I think). Given that `join` is used, "membership" seems like a close match to that for terminology. It does sound a bit awkward though (membership service?)

**Comment by vieux** [comment]
I agree, I think we should say Node Discovery service

**Comment by moxiegirl** [comment]
@vieux adding "node" to discovery service isn't really going to help.  Because the notion of service discovery is so dominant.  

Can someone define for me "discovery backend" I had this question when I started working the getting started docs and thought it meant service discovery. Is that the same or different than the topic here?

Don't "nodes join a swarm" that seems a natural way to say it.  Swarm service...or 'join a colony" meaning a particular swarm.  I definitely think we should find a way to remove the overloaded discovery --- register with a swarm....
