### ISSUE TITLE
How to reserve CPU

### ISSUE THREAD

**Issue by rachit1arora** [docker/swarm#534]
I am trying out swarm . I have built a swarm cluster using 2 nodes. 

I am able to reserve memory using -m option during run command , but i am not able to reserve cpu , i have tried cpuset="0-3" and cpuset="0" and cpuset="0,1" , none of these reserves a CPU , 

Here is the output from info command 
 docker -H tcp://10.ddd.yy.xx:2375 info

Containers: 12
Nodes: 2
 xxx-dev-008: 10..XXX.DD.ZZ:2375
  â Containers: 2
  â Reserved CPUs: 0 / 8
  â Reserved Memory: 2 GiB / 15.26 GiB
xxx-dev-003: 10.XXX.DD.YY:2375
  â Containers: 10
  â Reserved CPUs: 0 / 8
  â Reserved Memory: 0 B / 15.26 GiB

Here if we see Reserved CPUs is alway 0/8 where as Reserved Memory works as expected. 
I am using following command to run containers

docker -H tcp://<swarm-manager>:2375 run -m 2G --cpuset="0"  --name con24  -h test24.testrac.com centos:centos6 /bin/bash

docker -H tcp://<swarm-manager>:2375 run -m 1G --cpuset="0-3"  --name con25  -h test25.testrac.com centos:centos6 /bin/bash

Please let me know what i am missing to reserve the CPUs 

Thanks in advance for help !!

**Comment by aluzzardi** [comment]
It's not `cpuset` but cpushares `-c`. Just do `-c NumberOfCPUCoresYouWant` and you should be good to go.

**Comment by ch3lo** [comment]
Why -c? If I'm right, -c by default is 1024 and it is a relative weight to others containers.

**Comment by xFragger** [comment]
Same question for me. I've got a cluster, every node has one CPU and i want to reserve 1/4 for each container, so that the max is 4 containers per node. So i thought i could give --cpu-shared 256 to each "run"-command, to sum up to 1024

--cpu-shares would be ok, if it would accept floats, but it does not, or even i could manipulate the amount of available CPUs per node

**Comment by abronan** [comment]
@xFragger There is a conversion that is made from `-c` in swarm to `--cpu-shares` in docker. When you specify `-c 1` in swarm it traduces to `--cpu-shares 256` for docker. `-c` and `-m` are one of the rare flags that are a bit different in how they function from a swarm perspective.

Otherwise you can still use `--cpu-quotas` for example but cpu time will not be accounted by the scheduler, this is a possible enhancement to consider on the swarm side.

**Comment by xFragger** [comment]
i saw the conversation, after commenting here....
my problem is, that i want to control the max number of containers per node, i thought, using the cpu could be a solution, but it isnt.... is there another possibility to control this number?
Normally all possible nodes, that i address with a "run" call (with constraints for some labels), are of the same kind and all of them should run a fixed number of containers, if the number is reached and no more nodes are matching, it should cancel the creation with the typical "no node found" error

**Comment by abronan** [comment]
@xFragger I think your use case is very typical and does not really fit using `-c` because it would be just a workaround to limit for a raw number of containers per node using cpu resource reservation.

Do you mind opening a short proposal (in a new issue) for this? I mean maybe we can use labels to specify the maximum number of containers per node and make the scheduler aware of that when using filters.

**Comment by dongluochen** [comment]
@xFragger I had a similar case and I used memory limit to do it. I can only run 4 instances of the following command to use up 4 GB memory on the node.  
```
dchen@vm4:~$ ./docker -H vm2:2372 run  -m 1G -d busybox sh
de884da33e794b3b507a9bac62a8650196e9cc83e4f048127fbcd06b3313e54c
dchen@vm4:~$ ./docker -H vm2:2372 info
Containers: 18
 Running: 0
 Paused: 0
 Stopped: 18
Images: 19
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 1
 vm3: xxx.xxx.xxx.xxx:4444
  └ Status: Healthy
  └ Containers: 18
  └ Reserved CPUs: 1 / 2
  └ Reserved Memory: 1 GiB / 4.053 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.19.0-25-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-02-03T21:44:12Z
Plugins: 
 Volume: 
 Network: 
Kernel Version: 3.19.0-25-generic
Operating System: linux
Architecture: amd64
CPUs: 2
Total Memory: 4.053 GiB
Name: vm2
Experimental: true
```
