### ISSUE TITLE
Proposal: Add a Retry Filter

### ISSUE THREAD

**Issue by jimmyxian** [docker/swarm#568]
### Proposal: Retry Filter
When we create a container, if fails on a selected node(such as pull image failed...), then the create task will fail. I think that is not good, the cluster should try another node to do the create task.So I propose to have Retry Filter to do this.

### Implement steps:
* (1) Add two interfaces(IsTried() and SetTry(tried bool)) in Node interface(node.go). This two interfaces mainly maintain a bool variable which used to mark whether this node is tried.
* (2) Add a RetryFilter(retry.go).  Used to filter nodes(IsTried() == false)
* (3) Fix Scheduler flow.
    * Before scheduler: mark all nodes not tried (node.SetTry(false))
    * Scheduling: If faild and RetryFilter is in UserConf, mark this node istried(node.SetTry(true)), and get another node to try

Any thoughts if this will be useful?

**Comment by vieux** [comment]
I can understand the need, but I don't think retry should be a `filter` it's not really filtering.

/cc @abronan @aluzzardi

**Comment by abronan** [comment]
True, I don't think it belongs to the filtering part even though this can be useful.

**Comment by aluzzardi** [comment]
Thanks @jimmyxian 

A few comments on the proposed implementation:

* As Victor mentioned, this doesn't belong to filters
* The problem with adding that boolean to Node is that it will break parallel scheduling since Node objects are the same. The alternative would be to either use a separate structure for the scheduler (filled from the Nodes, but the scheduler can fiddle around with them), or simply maintaining a map `SelectNodeForContainer`

As for the feature itself, it's a little tricky: how would you define a re-triable error? For instance, if the image doesn't exist at all we shouldn't retry.

**Comment by jimmyxian** [comment]
Thanks @vieux  @abronan  @aluzzardi . 
I got it...
* First: Not a filter
* Second: Break the parallel scheduling
* Third: Not have a clear way to define failed

I will rethink about it....   :)

**Comment by aluzzardi** [comment]
Thanks @jimmyxian 

Please re-open this issue or open a new one once you are ready to restart the conversation!
