### ISSUE TITLE
Remove a cluster from docker swarm

### ISSUE THREAD

**Issue by sourav82** [docker/swarm#580]
Is there any API/ workaround to remove a docker cluster from swarm (say, swarm remove token://<clusterId>) or de-register a specific node from a cluster (say swarm leave --addr=... token://...) ?

**Comment by mgoelzer** [comment]
@sourav82, with etcd discovery, a node is deleted automatically if it doesn't check in periodically.  I don't think the (default) token discovery mechanism supports this.  You can delete the entire swarm by doing "curl -XDELETE https://discovery-stage.hub.docker.com/v1/clusters/<put token here...>" although that doesn't work for me because postgres on Docker Hub is having problems right now (probably related to issue #577 ?).

**Comment by qicongchen** [comment]
Hi @mgoelzer, I used etcd for discovery. When a node is down, its info is removed from etcd, but still exists in docker info (on swarm manager). Any way to fix this?Thanks!

**Comment by abronan** [comment]
Hi @qicongchen, this is related to #197 and the node removal feature. Actually the manager does not remove the node entry from its list according to the state of the discovery service. We plan to have it soon. I'll close this issue again but feel free to comment on the issue I linked :)
