### ISSUE TITLE
Local version of Discovery Service

### ISSUE THREAD

**Issue by arun-gupta** [docker/swarm#660]
Is there a way by which Swarm cluster can be created by pointing to a Discovery Service that is hosted inside the firewall? Basically, make Discovery Service as another Docker image that can run inside the firewall.

This can be useful for default installations where they don't have to (want to?) get into etcd, consul, or zookeper.

**Comment by aluzzardi** [comment]
Some background: The API the discovery service is using is entirely [open](https://github.com/docker/swarm/blob/master/discovery/README.md) but the reason the implementation is not is because it has a dependency on storage (right now it's using our internal infrastructure storage) and so it wouldn't work anywhere else.

Even if we made it available, you would have to set up some kind of storage (consul, etcd, postgres, ...) for the discovery service to use, so it wouldn't solve that issue either.

**Comment by arun-gupta** [comment]
@aluzzardi This is very helpful. Can you share instructions on what it requires to setup storage to work with token-based service?

**Comment by aluzzardi** [comment]
The implementation we have internally uses PostgreSQL. consul/etcd/zookeeper are as simple to setup.

**Comment by arun-gupta** [comment]
Is there a contract that needs to be honored by these services?
