### ISSUE TITLE
Backward compatibility with labels

### ISSUE THREAD

**Issue by aluzzardi** [docker/swarm#699]
Right now, Swarm will fail when using docker < 1.5.

We should revert to environment variables when using older versions.

**Comment by aluzzardi** [comment]
@vieux we should discuss this together

**Comment by thaJeztah** [comment]
Or, add a compatibility table to the README; e.g. Swarm 0.2 supports docker <= 1.5, Swarm 0.3 supports Docker 1.6 and up.

This may "gently" push users to update their software to recent versions, reducing the burden of having to support old clients. People that refuse to (of cannot) upgrade Docker, can sill download an older version of Swarm.

Note; I suggested the same approach for compose, where similar issues arose because some features were only available in API 1.xx

**Comment by aluzzardi** [comment]
@thaJeztah Agreed!

**Comment by thaJeztah** [comment]
ping @moxiegirl (non urgent); wdyt on using such tables for the various projects?

**Comment by moxiegirl** [comment]
@thaJeztah I think it is a great idea. It would be nice to maintain it centrally some place --- the documentation is a good stop gap. If it is down in the readme we might miss the users that never go to the project areas.  I've seen people host them on support pages as well.  The commercial team might already have something. I an ask
