### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by UserTaken** [docker/swarm#797]
I have a old last gen Raspberry Pi that I thought would be suitable to run as a swarm master given its modest specs. There are Docker packages for ARM so I'm wondering if it's possible to have a `swarm` image for ARM and if so, control x86-64 Docker daemons through ARM `swarm` or will it be limited to ARM `docker`?

**Comment by aluzzardi** [comment]
Swarm could control any kind of Docker daemons (it doesn't care about the target arch as long as it speaks the same API).

We have no ARM image for Swarm but you could easily build an ARM binary (`git clone` + `godep go build`) and run it instead of using `docker run swarm` 

@chanwit used Swarm on a x86/ARM hybrid cluster

**Comment by chanwit** [comment]
@UserTaken you can just compile and run `swarm` on the ARM board. It just works with your x86-64 Docker deamons without any problem.

Side note: a Docker daemon would use around 500 MB of RAM at fully operation. So using the `swarm` binary is just better for a constraint machine.

@aluzzardi thank you for the ping :)

**Comment by UserTaken** [comment]
@chanwit and @aluzzardi Thanks for answering my questions.

**Comment by mastermindg** [comment]
Heads up that you'll need to adjust the timeout settings when compiling go on arm.
