### ISSUE TITLE
Swarm Cluster Created with Machine hangs, trying to deploy to cluster

### ISSUE THREAD

**Issue by myfear** [docker/swarm#869]
If I create a swarm cluster on windows with machine:

. docker run swarm create
. docker-machine create -d virtualbox --swarm --swarm-master --swarm-discovery token://<TOKEN> swarm-master
. docker-machine create -d virtualbox --swarm --swarm-discovery token://<TOKEN> swarm-node-01
. docker-machine create -d virtualbox --swarm --swarm-discovery token://<TOKEN> swarm-node-02

docker run swarm list token://<TOKEN> lists all my nodes:

192.168.99.102:2376
192.168.99.101:2376
192.168.99.103:2376

While being connected to the cluster: tcp://192.168.99.101:3376
Every docker run * command hangs.

docker run hello-world

Anything I can help with debugging?

**Comment by abronan** [comment]
Hi @myfear, thanks for reporting the issue. Is this really hanging (no output after a few minutes) or if you wait a little bit you finally see the hello-world output (appears like hanging)?

With swarm when you do a `docker run` it may pull the image in the background so it appears like hanging while it is indeed pulling the image.

Can you `docker info`/`docker version` or is this hanging too?

**Comment by myfear** [comment]
C:\Users\myfear>docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): windows/amd64
Server version: swarm/0.2.0
Go version (server): go1.3.3
Git commit (server): 48fd993
OS/Arch (server): linux/amd64

C:\Users\myfear>docker info
Containers: 5
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Nodes: 3
 swarm-master: 192.168.99.101:2376
  └ Containers: 2
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 1.025 GiB
 swarm-node-01: 192.168.99.102:2376
  └ Containers: 2
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 1.025 GiB
 swarm-node-02: 192.168.99.103:2376
  └ Containers: 1
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 1.025 GiB

You seem to be right, that the download is causing that "hang" feel. The hello-world example runs after a couple of minutes. If there's a chance to introduce something like a progress indicator, that would be helpful. 
Plus, while I docker run an image and try to list the nodes it seems, that the list nodes command is blocked.

**Comment by ehazlett** [comment]
Hi Markus,

It looks like you are running in virtualbox. Could you try shutting down the instances and changing the NIC driver for each interface to Intel E1000?  There were issues with the old driver that we fixed in Machine master (coming in 0.3). This may help with the performance.

**Comment by abronan** [comment]
@myfear Unfortunately, this is a limitation of the API, you can see the progress using `docker pull` directly but if you do this, this will pull the image on every machine. We hope to make the process less confusing using `docker run` if there is some improvement on the API side to stream progress on the underlying `pull` operation, you can take a look at the last comments on #336 for more details.

Also 15 minutes for the `hello-world` example seems really slow, on a moderate speed network this should take a few seconds at most. Do you have the same issue if you ssh into one of your Swarm agent and use the docker daemon directly? You can probably try the fix suggested on the comment above and see if it improves speed on your `docker-machine` setup.

______________

> Plus, while I docker run an image and try to "docker run swarm list" the nodes in another console window, that command is blocked.

`docker run swarm list` will be scheduled as any other container on your cluster. We made the decision for now to schedule containers each one at a time to avoid races at resource and name reservation (this will change and we'll eventually go back to parallelized scheduling of containers).

So what happens exactly is that when you schedule your first container with `docker run`, swarm will wait for the container to be effectively started, which in your case with a slow network could take some time because you need to wait for the image to be downloaded first. The scheduling decision for the second container (with `docker run swarm list`) will be blocked until Swarm has acknowledged that it effectively started and returned a unique ID for the first container.

**Comment by abronan** [comment]
Closing this for now, @myfear let us know if you still encounter this issue with the latest versions of `swarm` and `docker-machine`, thanks! :)
