### ISSUE TITLE
Swarm stress test is failing.

### ISSUE THREAD

**Issue by Pensu** [docker/swarm#919]
Hi all,

I am using swarm version 0.3.0 and docker version 1.6.2 on Ubuntu trusty.

Here are the concerned outputs:

swarm --version
swarm version 0.3.0 (HEAD)

docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

docker info
Containers: 0
Images: 11
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 11
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-53-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 994 MiB
Name: vagrant-ubuntu-trusty-64
ID: KVWO:RSGP:G4CA:IML5:MUCK:OE7J:DPRQ:RCRX:GAB6:SPFU:WGAG:XIX7
WARNING: No swap limit support

uname -a
Linux vagrant-ubuntu-trusty-64 3.13.0-53-generic #89-Ubuntu SMP Wed May 20 10:34:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

I have found two basic issues with swarm stress test.

1. At line 55: wait_until_swarm_joined $NODES, there is no function named wait_until_swarm_joined() in ../test/integration/helpers.bash, instead the function is by the name: swarm_join()

2. At line 60: [[ "${lines[3]}" == *"Nodes: $NODES" ]], the output of lines[3] is Strategy: Spread, it should be lines[5] which outputs to Nodes: 10.

Should I fix these and sent a pull request or wait for the issue to be triaged? This is my first time submitting an issue so apologies if there is any mistake.

**Comment by vieux** [comment]
ping @aluzzardi

**Comment by aluzzardi** [comment]
Hey @Pensu, thanks for the feedback! Glad you opened an issue.

stress tests were created a long time ago (a couple of months actually, but things move fast) but are not actively maintained simply because they are not run automatically (integration tests get triggered on every PR, but stress tests are manual). Since no one noticed they broke, no one fixed then.

Feel free to fix them - we should automate their usage soon enough.

1. I think there's no need of wait_until_swarm_joined anymore
2. Instead of hard-coding the line number (`${lines[3]})`, we should simply use `$output` which contains all the output (so it's not dependent on line numbers and won't break again when we change `docker info`

**Comment by Pensu** [comment]
Thanks for the reply @aluzzardi. I am on it!
