### ISSUE TITLE
ROADMAP out of date

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/swarm#978]
It says:

> ![image](https://cloud.githubusercontent.com/assets/159209/8259461/8a1a1bd6-1671-11e5-900f-6dcb49894466.png)

also there are other parts in it that are implemented with 0.3.0 but not marked as complete.

**Comment by aluzzardi** [comment]
Thanks @ahmetalpbalkan 

ping @amylindburg 

Should we get rid of `ROADMAP.md` and just link to the wiki? It gets out of date pretty quickly

**Comment by amylindburg** [comment]
@aluzzardi How about if we make the ROADMAP.md higher-level -- so it does not go out of date quickly? You can state your broader goals, and then the Project Pages will give the details on how you are meeting these goals. Then the ROADMAP.md document will complement the Project Pages.

For example, one high-level goal is getting Swarm hardened so that it can be used in Production. The ROADMAP.md can express your thoughts on how to get to this goal -- perhaps via identifying use cases that will be solved.

**Comment by ahmetalpbalkan** [comment]
Agreed on Amy's view + I'd like to see what the product is tackling in each sprint/release so people can try to help maintainers with those. I think this is something we already have in the roadmap, but a long term high level goal along with that would be nice.
